// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package tube

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Czar) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields0zgensym_d4b91a75c2094c05_1 = 3

	// -- templateDecodeMsg starts here--
	var totalEncodedFields0zgensym_d4b91a75c2094c05_1 uint32
	totalEncodedFields0zgensym_d4b91a75c2094c05_1, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft0zgensym_d4b91a75c2094c05_1 := totalEncodedFields0zgensym_d4b91a75c2094c05_1
	missingFieldsLeft0zgensym_d4b91a75c2094c05_1 := maxFields0zgensym_d4b91a75c2094c05_1 - totalEncodedFields0zgensym_d4b91a75c2094c05_1

	var nextMiss0zgensym_d4b91a75c2094c05_1 int32 = -1
	var found0zgensym_d4b91a75c2094c05_1 [maxFields0zgensym_d4b91a75c2094c05_1]bool
	var curField0zgensym_d4b91a75c2094c05_1 string

doneWithStruct0zgensym_d4b91a75c2094c05_1:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft0zgensym_d4b91a75c2094c05_1 > 0 || missingFieldsLeft0zgensym_d4b91a75c2094c05_1 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft0zgensym_d4b91a75c2094c05_1, missingFieldsLeft0zgensym_d4b91a75c2094c05_1, msgp.ShowFound(found0zgensym_d4b91a75c2094c05_1[:]), decodeMsgFieldOrder0zgensym_d4b91a75c2094c05_1)
		if encodedFieldsLeft0zgensym_d4b91a75c2094c05_1 > 0 {
			encodedFieldsLeft0zgensym_d4b91a75c2094c05_1--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField0zgensym_d4b91a75c2094c05_1 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss0zgensym_d4b91a75c2094c05_1 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss0zgensym_d4b91a75c2094c05_1 = 0
			}
			for nextMiss0zgensym_d4b91a75c2094c05_1 < maxFields0zgensym_d4b91a75c2094c05_1 && (found0zgensym_d4b91a75c2094c05_1[nextMiss0zgensym_d4b91a75c2094c05_1] || decodeMsgFieldSkip0zgensym_d4b91a75c2094c05_1[nextMiss0zgensym_d4b91a75c2094c05_1]) {
				nextMiss0zgensym_d4b91a75c2094c05_1++
			}
			if nextMiss0zgensym_d4b91a75c2094c05_1 == maxFields0zgensym_d4b91a75c2094c05_1 {
				// filled all the empty fields!
				break doneWithStruct0zgensym_d4b91a75c2094c05_1
			}
			missingFieldsLeft0zgensym_d4b91a75c2094c05_1--
			curField0zgensym_d4b91a75c2094c05_1 = decodeMsgFieldOrder0zgensym_d4b91a75c2094c05_1[nextMiss0zgensym_d4b91a75c2094c05_1]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField0zgensym_d4b91a75c2094c05_1)
		switch curField0zgensym_d4b91a75c2094c05_1 {
		// -- templateDecodeMsg ends here --

		case "TubeCliName_zid00_str":
			found0zgensym_d4b91a75c2094c05_1[0] = true
			z.TubeCliName, err = dc.ReadString()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss0zgensym_d4b91a75c2094c05_1 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Czar
var decodeMsgFieldOrder0zgensym_d4b91a75c2094c05_1 = []string{"TubeCliName_zid00_str", "", ""}

var decodeMsgFieldSkip0zgensym_d4b91a75c2094c05_1 = []bool{false, true, true}

// fieldsNotEmpty supports omitempty tags
func (z *Czar) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 1
	}
	var fieldsInUse uint32 = 1
	isempty[0] = (len(z.TubeCliName) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Czar) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_2 [3]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_3 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_2[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_3 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Czar'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x43, 0x7a, 0x61, 0x72})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_2[0] {
		// write "TubeCliName_zid00_str"
		err = en.Append(0xb5, 0x54, 0x75, 0x62, 0x65, 0x43, 0x6c, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.TubeCliName)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Czar) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "TubeCliName_zid00_str"
		o = append(o, 0xb5, 0x54, 0x75, 0x62, 0x65, 0x43, 0x6c, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.TubeCliName)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Czar) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Czar) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields4zgensym_d4b91a75c2094c05_5 = 3

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields4zgensym_d4b91a75c2094c05_5 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields4zgensym_d4b91a75c2094c05_5, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft4zgensym_d4b91a75c2094c05_5 := totalEncodedFields4zgensym_d4b91a75c2094c05_5
	missingFieldsLeft4zgensym_d4b91a75c2094c05_5 := maxFields4zgensym_d4b91a75c2094c05_5 - totalEncodedFields4zgensym_d4b91a75c2094c05_5

	var nextMiss4zgensym_d4b91a75c2094c05_5 int32 = -1
	var found4zgensym_d4b91a75c2094c05_5 [maxFields4zgensym_d4b91a75c2094c05_5]bool
	var curField4zgensym_d4b91a75c2094c05_5 string

doneWithStruct4zgensym_d4b91a75c2094c05_5:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft4zgensym_d4b91a75c2094c05_5 > 0 || missingFieldsLeft4zgensym_d4b91a75c2094c05_5 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft4zgensym_d4b91a75c2094c05_5, missingFieldsLeft4zgensym_d4b91a75c2094c05_5, msgp.ShowFound(found4zgensym_d4b91a75c2094c05_5[:]), unmarshalMsgFieldOrder4zgensym_d4b91a75c2094c05_5)
		if encodedFieldsLeft4zgensym_d4b91a75c2094c05_5 > 0 {
			encodedFieldsLeft4zgensym_d4b91a75c2094c05_5--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField4zgensym_d4b91a75c2094c05_5 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss4zgensym_d4b91a75c2094c05_5 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss4zgensym_d4b91a75c2094c05_5 = 0
			}
			for nextMiss4zgensym_d4b91a75c2094c05_5 < maxFields4zgensym_d4b91a75c2094c05_5 && (found4zgensym_d4b91a75c2094c05_5[nextMiss4zgensym_d4b91a75c2094c05_5] || unmarshalMsgFieldSkip4zgensym_d4b91a75c2094c05_5[nextMiss4zgensym_d4b91a75c2094c05_5]) {
				nextMiss4zgensym_d4b91a75c2094c05_5++
			}
			if nextMiss4zgensym_d4b91a75c2094c05_5 == maxFields4zgensym_d4b91a75c2094c05_5 {
				// filled all the empty fields!
				break doneWithStruct4zgensym_d4b91a75c2094c05_5
			}
			missingFieldsLeft4zgensym_d4b91a75c2094c05_5--
			curField4zgensym_d4b91a75c2094c05_5 = unmarshalMsgFieldOrder4zgensym_d4b91a75c2094c05_5[nextMiss4zgensym_d4b91a75c2094c05_5]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField4zgensym_d4b91a75c2094c05_5)
		switch curField4zgensym_d4b91a75c2094c05_5 {
		// -- templateUnmarshalMsg ends here --

		case "TubeCliName_zid00_str":
			found4zgensym_d4b91a75c2094c05_5[0] = true
			z.TubeCliName, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss4zgensym_d4b91a75c2094c05_5 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Czar
var unmarshalMsgFieldOrder4zgensym_d4b91a75c2094c05_5 = []string{"TubeCliName_zid00_str", "", ""}

var unmarshalMsgFieldSkip4zgensym_d4b91a75c2094c05_5 = []bool{false, true, true}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Czar) Msgsize() (s int) {
	s = 1 + 22 + msgp.StringPrefixSize + len(z.TubeCliName)
	return
}
func (z *Czar) Gstring() (r string) {
	r = "&Czar{\n"
	r += fmt.Sprintf("TubeCliName: \"%v\",\n", z.TubeCliName)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *RMVersionTuple) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields6zgensym_d4b91a75c2094c05_7 = 3

	// -- templateDecodeMsg starts here--
	var totalEncodedFields6zgensym_d4b91a75c2094c05_7 uint32
	totalEncodedFields6zgensym_d4b91a75c2094c05_7, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft6zgensym_d4b91a75c2094c05_7 := totalEncodedFields6zgensym_d4b91a75c2094c05_7
	missingFieldsLeft6zgensym_d4b91a75c2094c05_7 := maxFields6zgensym_d4b91a75c2094c05_7 - totalEncodedFields6zgensym_d4b91a75c2094c05_7

	var nextMiss6zgensym_d4b91a75c2094c05_7 int32 = -1
	var found6zgensym_d4b91a75c2094c05_7 [maxFields6zgensym_d4b91a75c2094c05_7]bool
	var curField6zgensym_d4b91a75c2094c05_7 string

doneWithStruct6zgensym_d4b91a75c2094c05_7:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft6zgensym_d4b91a75c2094c05_7 > 0 || missingFieldsLeft6zgensym_d4b91a75c2094c05_7 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft6zgensym_d4b91a75c2094c05_7, missingFieldsLeft6zgensym_d4b91a75c2094c05_7, msgp.ShowFound(found6zgensym_d4b91a75c2094c05_7[:]), decodeMsgFieldOrder6zgensym_d4b91a75c2094c05_7)
		if encodedFieldsLeft6zgensym_d4b91a75c2094c05_7 > 0 {
			encodedFieldsLeft6zgensym_d4b91a75c2094c05_7--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField6zgensym_d4b91a75c2094c05_7 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss6zgensym_d4b91a75c2094c05_7 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss6zgensym_d4b91a75c2094c05_7 = 0
			}
			for nextMiss6zgensym_d4b91a75c2094c05_7 < maxFields6zgensym_d4b91a75c2094c05_7 && (found6zgensym_d4b91a75c2094c05_7[nextMiss6zgensym_d4b91a75c2094c05_7] || decodeMsgFieldSkip6zgensym_d4b91a75c2094c05_7[nextMiss6zgensym_d4b91a75c2094c05_7]) {
				nextMiss6zgensym_d4b91a75c2094c05_7++
			}
			if nextMiss6zgensym_d4b91a75c2094c05_7 == maxFields6zgensym_d4b91a75c2094c05_7 {
				// filled all the empty fields!
				break doneWithStruct6zgensym_d4b91a75c2094c05_7
			}
			missingFieldsLeft6zgensym_d4b91a75c2094c05_7--
			curField6zgensym_d4b91a75c2094c05_7 = decodeMsgFieldOrder6zgensym_d4b91a75c2094c05_7[nextMiss6zgensym_d4b91a75c2094c05_7]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField6zgensym_d4b91a75c2094c05_7)
		switch curField6zgensym_d4b91a75c2094c05_7 {
		// -- templateDecodeMsg ends here --

		case "CzarLeaseEpoch_zid00_i64":
			found6zgensym_d4b91a75c2094c05_7[0] = true
			z.CzarLeaseEpoch, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "Version_zid01_i64":
			found6zgensym_d4b91a75c2094c05_7[1] = true
			z.Version, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "LeaseUpdateCounter_zid02_i64":
			found6zgensym_d4b91a75c2094c05_7[2] = true
			z.LeaseUpdateCounter, err = dc.ReadInt64()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss6zgensym_d4b91a75c2094c05_7 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of RMVersionTuple
var decodeMsgFieldOrder6zgensym_d4b91a75c2094c05_7 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var decodeMsgFieldSkip6zgensym_d4b91a75c2094c05_7 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *RMVersionTuple) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 3
	}
	var fieldsInUse uint32 = 3
	isempty[0] = (z.CzarLeaseEpoch == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.Version == 0) // number, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.LeaseUpdateCounter == 0) // number, omitempty
	if isempty[2] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *RMVersionTuple) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_8 [3]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_9 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_8[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_9 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'RMVersionTuple'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x52, 0x4d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_8[0] {
		// write "CzarLeaseEpoch_zid00_i64"
		err = en.Append(0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.CzarLeaseEpoch)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_8[1] {
		// write "Version_zid01_i64"
		err = en.Append(0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.Version)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_8[2] {
		// write "LeaseUpdateCounter_zid02_i64"
		err = en.Append(0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.LeaseUpdateCounter)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RMVersionTuple) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "CzarLeaseEpoch_zid00_i64"
		o = append(o, 0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.CzarLeaseEpoch)
	}

	if !empty[1] {
		// string "Version_zid01_i64"
		o = append(o, 0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.Version)
	}

	if !empty[2] {
		// string "LeaseUpdateCounter_zid02_i64"
		o = append(o, 0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.LeaseUpdateCounter)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RMVersionTuple) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *RMVersionTuple) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields10zgensym_d4b91a75c2094c05_11 = 3

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields10zgensym_d4b91a75c2094c05_11 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields10zgensym_d4b91a75c2094c05_11, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft10zgensym_d4b91a75c2094c05_11 := totalEncodedFields10zgensym_d4b91a75c2094c05_11
	missingFieldsLeft10zgensym_d4b91a75c2094c05_11 := maxFields10zgensym_d4b91a75c2094c05_11 - totalEncodedFields10zgensym_d4b91a75c2094c05_11

	var nextMiss10zgensym_d4b91a75c2094c05_11 int32 = -1
	var found10zgensym_d4b91a75c2094c05_11 [maxFields10zgensym_d4b91a75c2094c05_11]bool
	var curField10zgensym_d4b91a75c2094c05_11 string

doneWithStruct10zgensym_d4b91a75c2094c05_11:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft10zgensym_d4b91a75c2094c05_11 > 0 || missingFieldsLeft10zgensym_d4b91a75c2094c05_11 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft10zgensym_d4b91a75c2094c05_11, missingFieldsLeft10zgensym_d4b91a75c2094c05_11, msgp.ShowFound(found10zgensym_d4b91a75c2094c05_11[:]), unmarshalMsgFieldOrder10zgensym_d4b91a75c2094c05_11)
		if encodedFieldsLeft10zgensym_d4b91a75c2094c05_11 > 0 {
			encodedFieldsLeft10zgensym_d4b91a75c2094c05_11--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField10zgensym_d4b91a75c2094c05_11 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss10zgensym_d4b91a75c2094c05_11 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss10zgensym_d4b91a75c2094c05_11 = 0
			}
			for nextMiss10zgensym_d4b91a75c2094c05_11 < maxFields10zgensym_d4b91a75c2094c05_11 && (found10zgensym_d4b91a75c2094c05_11[nextMiss10zgensym_d4b91a75c2094c05_11] || unmarshalMsgFieldSkip10zgensym_d4b91a75c2094c05_11[nextMiss10zgensym_d4b91a75c2094c05_11]) {
				nextMiss10zgensym_d4b91a75c2094c05_11++
			}
			if nextMiss10zgensym_d4b91a75c2094c05_11 == maxFields10zgensym_d4b91a75c2094c05_11 {
				// filled all the empty fields!
				break doneWithStruct10zgensym_d4b91a75c2094c05_11
			}
			missingFieldsLeft10zgensym_d4b91a75c2094c05_11--
			curField10zgensym_d4b91a75c2094c05_11 = unmarshalMsgFieldOrder10zgensym_d4b91a75c2094c05_11[nextMiss10zgensym_d4b91a75c2094c05_11]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField10zgensym_d4b91a75c2094c05_11)
		switch curField10zgensym_d4b91a75c2094c05_11 {
		// -- templateUnmarshalMsg ends here --

		case "CzarLeaseEpoch_zid00_i64":
			found10zgensym_d4b91a75c2094c05_11[0] = true
			z.CzarLeaseEpoch, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "Version_zid01_i64":
			found10zgensym_d4b91a75c2094c05_11[1] = true
			z.Version, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "LeaseUpdateCounter_zid02_i64":
			found10zgensym_d4b91a75c2094c05_11[2] = true
			z.LeaseUpdateCounter, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss10zgensym_d4b91a75c2094c05_11 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of RMVersionTuple
var unmarshalMsgFieldOrder10zgensym_d4b91a75c2094c05_11 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var unmarshalMsgFieldSkip10zgensym_d4b91a75c2094c05_11 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RMVersionTuple) Msgsize() (s int) {
	s = 1 + 25 + msgp.Int64Size + 18 + msgp.Int64Size + 29 + msgp.Int64Size
	return
}
func (z *RMVersionTuple) Gstring() (r string) {
	r = "&RMVersionTuple{\n"
	r += fmt.Sprintf("    CzarLeaseEpoch: %v,\n", z.CzarLeaseEpoch)
	r += fmt.Sprintf("           Version: %v,\n", z.Version)
	r += fmt.Sprintf("LeaseUpdateCounter: %v,\n", z.LeaseUpdateCounter)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *ReliableMembershipList) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields13zgensym_d4b91a75c2094c05_14 = 4

	// -- templateDecodeMsg starts here--
	var totalEncodedFields13zgensym_d4b91a75c2094c05_14 uint32
	totalEncodedFields13zgensym_d4b91a75c2094c05_14, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft13zgensym_d4b91a75c2094c05_14 := totalEncodedFields13zgensym_d4b91a75c2094c05_14
	missingFieldsLeft13zgensym_d4b91a75c2094c05_14 := maxFields13zgensym_d4b91a75c2094c05_14 - totalEncodedFields13zgensym_d4b91a75c2094c05_14

	var nextMiss13zgensym_d4b91a75c2094c05_14 int32 = -1
	var found13zgensym_d4b91a75c2094c05_14 [maxFields13zgensym_d4b91a75c2094c05_14]bool
	var curField13zgensym_d4b91a75c2094c05_14 string

doneWithStruct13zgensym_d4b91a75c2094c05_14:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft13zgensym_d4b91a75c2094c05_14 > 0 || missingFieldsLeft13zgensym_d4b91a75c2094c05_14 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft13zgensym_d4b91a75c2094c05_14, missingFieldsLeft13zgensym_d4b91a75c2094c05_14, msgp.ShowFound(found13zgensym_d4b91a75c2094c05_14[:]), decodeMsgFieldOrder13zgensym_d4b91a75c2094c05_14)
		if encodedFieldsLeft13zgensym_d4b91a75c2094c05_14 > 0 {
			encodedFieldsLeft13zgensym_d4b91a75c2094c05_14--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField13zgensym_d4b91a75c2094c05_14 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss13zgensym_d4b91a75c2094c05_14 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss13zgensym_d4b91a75c2094c05_14 = 0
			}
			for nextMiss13zgensym_d4b91a75c2094c05_14 < maxFields13zgensym_d4b91a75c2094c05_14 && (found13zgensym_d4b91a75c2094c05_14[nextMiss13zgensym_d4b91a75c2094c05_14] || decodeMsgFieldSkip13zgensym_d4b91a75c2094c05_14[nextMiss13zgensym_d4b91a75c2094c05_14]) {
				nextMiss13zgensym_d4b91a75c2094c05_14++
			}
			if nextMiss13zgensym_d4b91a75c2094c05_14 == maxFields13zgensym_d4b91a75c2094c05_14 {
				// filled all the empty fields!
				break doneWithStruct13zgensym_d4b91a75c2094c05_14
			}
			missingFieldsLeft13zgensym_d4b91a75c2094c05_14--
			curField13zgensym_d4b91a75c2094c05_14 = decodeMsgFieldOrder13zgensym_d4b91a75c2094c05_14[nextMiss13zgensym_d4b91a75c2094c05_14]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField13zgensym_d4b91a75c2094c05_14)
		switch curField13zgensym_d4b91a75c2094c05_14 {
		// -- templateDecodeMsg ends here --

		case "CzarName_zid00_str":
			found13zgensym_d4b91a75c2094c05_14[0] = true
			z.CzarName, err = dc.ReadString()
			if err != nil {
				return
			}
		case "Vers_zid01_rct":
			found13zgensym_d4b91a75c2094c05_14[1] = true
			const maxFields15zgensym_d4b91a75c2094c05_16 = 3

			// -- templateDecodeMsg starts here--
			var totalEncodedFields15zgensym_d4b91a75c2094c05_16 uint32
			totalEncodedFields15zgensym_d4b91a75c2094c05_16, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			encodedFieldsLeft15zgensym_d4b91a75c2094c05_16 := totalEncodedFields15zgensym_d4b91a75c2094c05_16
			missingFieldsLeft15zgensym_d4b91a75c2094c05_16 := maxFields15zgensym_d4b91a75c2094c05_16 - totalEncodedFields15zgensym_d4b91a75c2094c05_16

			var nextMiss15zgensym_d4b91a75c2094c05_16 int32 = -1
			var found15zgensym_d4b91a75c2094c05_16 [maxFields15zgensym_d4b91a75c2094c05_16]bool
			var curField15zgensym_d4b91a75c2094c05_16 string

		doneWithStruct15zgensym_d4b91a75c2094c05_16:
			// First fill all the encoded fields, then
			// treat the remaining, missing fields, as Nil.
			for encodedFieldsLeft15zgensym_d4b91a75c2094c05_16 > 0 || missingFieldsLeft15zgensym_d4b91a75c2094c05_16 > 0 {
				//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft15zgensym_d4b91a75c2094c05_16, missingFieldsLeft15zgensym_d4b91a75c2094c05_16, msgp.ShowFound(found15zgensym_d4b91a75c2094c05_16[:]), decodeMsgFieldOrder15zgensym_d4b91a75c2094c05_16)
				if encodedFieldsLeft15zgensym_d4b91a75c2094c05_16 > 0 {
					encodedFieldsLeft15zgensym_d4b91a75c2094c05_16--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						return
					}
					curField15zgensym_d4b91a75c2094c05_16 = msgp.UnsafeString(field)
				} else {
					//missing fields need handling
					if nextMiss15zgensym_d4b91a75c2094c05_16 < 0 {
						// tell the reader to only give us Nils
						// until further notice.
						dc.PushAlwaysNil()
						nextMiss15zgensym_d4b91a75c2094c05_16 = 0
					}
					for nextMiss15zgensym_d4b91a75c2094c05_16 < maxFields15zgensym_d4b91a75c2094c05_16 && (found15zgensym_d4b91a75c2094c05_16[nextMiss15zgensym_d4b91a75c2094c05_16] || decodeMsgFieldSkip15zgensym_d4b91a75c2094c05_16[nextMiss15zgensym_d4b91a75c2094c05_16]) {
						nextMiss15zgensym_d4b91a75c2094c05_16++
					}
					if nextMiss15zgensym_d4b91a75c2094c05_16 == maxFields15zgensym_d4b91a75c2094c05_16 {
						// filled all the empty fields!
						break doneWithStruct15zgensym_d4b91a75c2094c05_16
					}
					missingFieldsLeft15zgensym_d4b91a75c2094c05_16--
					curField15zgensym_d4b91a75c2094c05_16 = decodeMsgFieldOrder15zgensym_d4b91a75c2094c05_16[nextMiss15zgensym_d4b91a75c2094c05_16]
				}
				//fmt.Printf("switching on curField: '%v'\n", curField15zgensym_d4b91a75c2094c05_16)
				switch curField15zgensym_d4b91a75c2094c05_16 {
				// -- templateDecodeMsg ends here --

				case "CzarLeaseEpoch_zid00_i64":
					found15zgensym_d4b91a75c2094c05_16[0] = true
					z.Vers.CzarLeaseEpoch, err = dc.ReadInt64()
					if err != nil {
						return
					}
				case "Version_zid01_i64":
					found15zgensym_d4b91a75c2094c05_16[1] = true
					z.Vers.Version, err = dc.ReadInt64()
					if err != nil {
						return
					}
				case "LeaseUpdateCounter_zid02_i64":
					found15zgensym_d4b91a75c2094c05_16[2] = true
					z.Vers.LeaseUpdateCounter, err = dc.ReadInt64()
					if err != nil {
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						return
					}
				}
			}
			if nextMiss15zgensym_d4b91a75c2094c05_16 != -1 {
				dc.PopAlwaysNil()
			}

		case "SerzPeerDetails_zid02_slc":
			found13zgensym_d4b91a75c2094c05_14[2] = true
			var zgensym_d4b91a75c2094c05_17 uint32
			zgensym_d4b91a75c2094c05_17, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.SerzPeerDetails) >= int(zgensym_d4b91a75c2094c05_17) {
				z.SerzPeerDetails = (z.SerzPeerDetails)[:zgensym_d4b91a75c2094c05_17]
			} else {
				z.SerzPeerDetails = make([]*PeerDetail, zgensym_d4b91a75c2094c05_17)
			}
			for zgensym_d4b91a75c2094c05_12 := range z.SerzPeerDetails {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}

					if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] != nil {
						dc.PushAlwaysNil()
						err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].DecodeMsg(dc)
						if err != nil {
							return
						}
						dc.PopAlwaysNil()
					}
				} else {
					// not Nil, we have something to read

					if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] == nil {
						z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] = new(PeerDetail)
					}
					dc.DedupIndexEachPtr(z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12])

					err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].DecodeMsg(dc)
					if err != nil {
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss13zgensym_d4b91a75c2094c05_14 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of ReliableMembershipList
var decodeMsgFieldOrder13zgensym_d4b91a75c2094c05_14 = []string{"CzarName_zid00_str", "Vers_zid01_rct", "SerzPeerDetails_zid02_slc", ""}

var decodeMsgFieldSkip13zgensym_d4b91a75c2094c05_14 = []bool{false, false, false, true}

// fields of RMVersionTuple
var decodeMsgFieldOrder15zgensym_d4b91a75c2094c05_16 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var decodeMsgFieldSkip15zgensym_d4b91a75c2094c05_16 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *ReliableMembershipList) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 3
	}
	var fieldsInUse uint32 = 3
	isempty[0] = (len(z.CzarName) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = false // struct values are never empty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.SerzPeerDetails) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *ReliableMembershipList) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_18 [4]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_19 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_18[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_19 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'ReliableMembershipList'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_18[0] {
		// write "CzarName_zid00_str"
		err = en.Append(0xb2, 0x43, 0x7a, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.CzarName)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_18[1] {
		// write "Vers_zid01_rct"
		err = en.Append(0xae, 0x56, 0x65, 0x72, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x72, 0x63, 0x74)
		if err != nil {
			return err
		}

		// honor the omitempty tags
		var empty_zgensym_d4b91a75c2094c05_20 [3]bool
		fieldsInUse_zgensym_d4b91a75c2094c05_21 := z.Vers.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_20[:])

		// map header
		err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_21 + 1)
		if err != nil {
			return err
		}

		// runtime struct type identification for 'RMVersionTuple'
		err = en.Append(0xa1, 0x40)
		if err != nil {
			return err
		}
		err = en.WriteStringFromBytes([]byte{0x52, 0x4d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65})
		if err != nil {
			return err
		}

		if !empty_zgensym_d4b91a75c2094c05_20[0] {
			// write "CzarLeaseEpoch_zid00_i64"
			err = en.Append(0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteInt64(z.Vers.CzarLeaseEpoch)
			if err != nil {
				return
			}
		}

		if !empty_zgensym_d4b91a75c2094c05_20[1] {
			// write "Version_zid01_i64"
			err = en.Append(0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteInt64(z.Vers.Version)
			if err != nil {
				return
			}
		}

		if !empty_zgensym_d4b91a75c2094c05_20[2] {
			// write "LeaseUpdateCounter_zid02_i64"
			err = en.Append(0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteInt64(z.Vers.LeaseUpdateCounter)
			if err != nil {
				return
			}
		}

	}

	if !empty_zgensym_d4b91a75c2094c05_18[2] {
		// write "SerzPeerDetails_zid02_slc"
		err = en.Append(0xb9, 0x53, 0x65, 0x72, 0x7a, 0x50, 0x65, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x6c, 0x63)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.SerzPeerDetails)))
		if err != nil {
			return
		}
		for zgensym_d4b91a75c2094c05_12 := range z.SerzPeerDetails {
			// gPtr.encodeGen():

			if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ReliableMembershipList) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [4]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "CzarName_zid00_str"
		o = append(o, 0xb2, 0x43, 0x7a, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.CzarName)
	}

	if !empty[1] {
		// string "Vers_zid01_rct"
		o = append(o, 0xae, 0x56, 0x65, 0x72, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x72, 0x63, 0x74)

		// honor the omitempty tags
		var empty [3]bool
		fieldsInUse := z.Vers.fieldsNotEmpty(empty[:])
		o = msgp.AppendMapHeader(o, fieldsInUse)

		if !empty[0] {
			// string "CzarLeaseEpoch_zid00_i64"
			o = append(o, 0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
			o = msgp.AppendInt64(o, z.Vers.CzarLeaseEpoch)
		}

		if !empty[1] {
			// string "Version_zid01_i64"
			o = append(o, 0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
			o = msgp.AppendInt64(o, z.Vers.Version)
		}

		if !empty[2] {
			// string "LeaseUpdateCounter_zid02_i64"
			o = append(o, 0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
			o = msgp.AppendInt64(o, z.Vers.LeaseUpdateCounter)
		}

	}

	if !empty[2] {
		// string "SerzPeerDetails_zid02_slc"
		o = append(o, 0xb9, 0x53, 0x65, 0x72, 0x7a, 0x50, 0x65, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x6c, 0x63)
		o = msgp.AppendArrayHeader(o, uint32(len(z.SerzPeerDetails)))
		for zgensym_d4b91a75c2094c05_12 := range z.SerzPeerDetails {
			// marshalGen.gPtr()

			if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] == nil {
				o = msgp.AppendNil(o)
			} else {
				// hmm.. no en, no place to check en.DedupWriteIsDup(z)

				o, err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].MarshalMsg(o) // not is.iface
				if err != nil {
					return
				}
			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReliableMembershipList) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *ReliableMembershipList) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields22zgensym_d4b91a75c2094c05_23 = 4

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields22zgensym_d4b91a75c2094c05_23 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields22zgensym_d4b91a75c2094c05_23, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft22zgensym_d4b91a75c2094c05_23 := totalEncodedFields22zgensym_d4b91a75c2094c05_23
	missingFieldsLeft22zgensym_d4b91a75c2094c05_23 := maxFields22zgensym_d4b91a75c2094c05_23 - totalEncodedFields22zgensym_d4b91a75c2094c05_23

	var nextMiss22zgensym_d4b91a75c2094c05_23 int32 = -1
	var found22zgensym_d4b91a75c2094c05_23 [maxFields22zgensym_d4b91a75c2094c05_23]bool
	var curField22zgensym_d4b91a75c2094c05_23 string

doneWithStruct22zgensym_d4b91a75c2094c05_23:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft22zgensym_d4b91a75c2094c05_23 > 0 || missingFieldsLeft22zgensym_d4b91a75c2094c05_23 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft22zgensym_d4b91a75c2094c05_23, missingFieldsLeft22zgensym_d4b91a75c2094c05_23, msgp.ShowFound(found22zgensym_d4b91a75c2094c05_23[:]), unmarshalMsgFieldOrder22zgensym_d4b91a75c2094c05_23)
		if encodedFieldsLeft22zgensym_d4b91a75c2094c05_23 > 0 {
			encodedFieldsLeft22zgensym_d4b91a75c2094c05_23--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField22zgensym_d4b91a75c2094c05_23 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss22zgensym_d4b91a75c2094c05_23 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss22zgensym_d4b91a75c2094c05_23 = 0
			}
			for nextMiss22zgensym_d4b91a75c2094c05_23 < maxFields22zgensym_d4b91a75c2094c05_23 && (found22zgensym_d4b91a75c2094c05_23[nextMiss22zgensym_d4b91a75c2094c05_23] || unmarshalMsgFieldSkip22zgensym_d4b91a75c2094c05_23[nextMiss22zgensym_d4b91a75c2094c05_23]) {
				nextMiss22zgensym_d4b91a75c2094c05_23++
			}
			if nextMiss22zgensym_d4b91a75c2094c05_23 == maxFields22zgensym_d4b91a75c2094c05_23 {
				// filled all the empty fields!
				break doneWithStruct22zgensym_d4b91a75c2094c05_23
			}
			missingFieldsLeft22zgensym_d4b91a75c2094c05_23--
			curField22zgensym_d4b91a75c2094c05_23 = unmarshalMsgFieldOrder22zgensym_d4b91a75c2094c05_23[nextMiss22zgensym_d4b91a75c2094c05_23]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField22zgensym_d4b91a75c2094c05_23)
		switch curField22zgensym_d4b91a75c2094c05_23 {
		// -- templateUnmarshalMsg ends here --

		case "CzarName_zid00_str":
			found22zgensym_d4b91a75c2094c05_23[0] = true
			z.CzarName, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "Vers_zid01_rct":
			found22zgensym_d4b91a75c2094c05_23[1] = true
			const maxFields24zgensym_d4b91a75c2094c05_25 = 3

			// -- templateUnmarshalMsg starts here--
			var totalEncodedFields24zgensym_d4b91a75c2094c05_25 uint32
			if !nbs.AlwaysNil {
				totalEncodedFields24zgensym_d4b91a75c2094c05_25, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
			}
			encodedFieldsLeft24zgensym_d4b91a75c2094c05_25 := totalEncodedFields24zgensym_d4b91a75c2094c05_25
			missingFieldsLeft24zgensym_d4b91a75c2094c05_25 := maxFields24zgensym_d4b91a75c2094c05_25 - totalEncodedFields24zgensym_d4b91a75c2094c05_25

			var nextMiss24zgensym_d4b91a75c2094c05_25 int32 = -1
			var found24zgensym_d4b91a75c2094c05_25 [maxFields24zgensym_d4b91a75c2094c05_25]bool
			var curField24zgensym_d4b91a75c2094c05_25 string

		doneWithStruct24zgensym_d4b91a75c2094c05_25:
			// First fill all the encoded fields, then
			// treat the remaining, missing fields, as Nil.
			for encodedFieldsLeft24zgensym_d4b91a75c2094c05_25 > 0 || missingFieldsLeft24zgensym_d4b91a75c2094c05_25 > 0 {
				//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft24zgensym_d4b91a75c2094c05_25, missingFieldsLeft24zgensym_d4b91a75c2094c05_25, msgp.ShowFound(found24zgensym_d4b91a75c2094c05_25[:]), unmarshalMsgFieldOrder24zgensym_d4b91a75c2094c05_25)
				if encodedFieldsLeft24zgensym_d4b91a75c2094c05_25 > 0 {
					encodedFieldsLeft24zgensym_d4b91a75c2094c05_25--
					field, bts, err = nbs.ReadMapKeyZC(bts)
					if err != nil {
						return
					}
					curField24zgensym_d4b91a75c2094c05_25 = msgp.UnsafeString(field)
				} else {
					//missing fields need handling
					if nextMiss24zgensym_d4b91a75c2094c05_25 < 0 {
						// set bts to contain just mnil (0xc0)
						bts = nbs.PushAlwaysNil(bts)
						nextMiss24zgensym_d4b91a75c2094c05_25 = 0
					}
					for nextMiss24zgensym_d4b91a75c2094c05_25 < maxFields24zgensym_d4b91a75c2094c05_25 && (found24zgensym_d4b91a75c2094c05_25[nextMiss24zgensym_d4b91a75c2094c05_25] || unmarshalMsgFieldSkip24zgensym_d4b91a75c2094c05_25[nextMiss24zgensym_d4b91a75c2094c05_25]) {
						nextMiss24zgensym_d4b91a75c2094c05_25++
					}
					if nextMiss24zgensym_d4b91a75c2094c05_25 == maxFields24zgensym_d4b91a75c2094c05_25 {
						// filled all the empty fields!
						break doneWithStruct24zgensym_d4b91a75c2094c05_25
					}
					missingFieldsLeft24zgensym_d4b91a75c2094c05_25--
					curField24zgensym_d4b91a75c2094c05_25 = unmarshalMsgFieldOrder24zgensym_d4b91a75c2094c05_25[nextMiss24zgensym_d4b91a75c2094c05_25]
				}
				//fmt.Printf("switching on curField: '%v'\n", curField24zgensym_d4b91a75c2094c05_25)
				switch curField24zgensym_d4b91a75c2094c05_25 {
				// -- templateUnmarshalMsg ends here --

				case "CzarLeaseEpoch_zid00_i64":
					found24zgensym_d4b91a75c2094c05_25[0] = true
					z.Vers.CzarLeaseEpoch, bts, err = nbs.ReadInt64Bytes(bts)

					if err != nil {
						return
					}
				case "Version_zid01_i64":
					found24zgensym_d4b91a75c2094c05_25[1] = true
					z.Vers.Version, bts, err = nbs.ReadInt64Bytes(bts)

					if err != nil {
						return
					}
				case "LeaseUpdateCounter_zid02_i64":
					found24zgensym_d4b91a75c2094c05_25[2] = true
					z.Vers.LeaseUpdateCounter, bts, err = nbs.ReadInt64Bytes(bts)

					if err != nil {
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						return
					}
				}
			}
			if nextMiss24zgensym_d4b91a75c2094c05_25 != -1 {
				bts = nbs.PopAlwaysNil()
			}

		case "SerzPeerDetails_zid02_slc":
			found22zgensym_d4b91a75c2094c05_23[2] = true
			if nbs.AlwaysNil {
				(z.SerzPeerDetails) = (z.SerzPeerDetails)[:0]
			} else {

				var zgensym_d4b91a75c2094c05_26 uint32
				zgensym_d4b91a75c2094c05_26, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.SerzPeerDetails) >= int(zgensym_d4b91a75c2094c05_26) {
					z.SerzPeerDetails = (z.SerzPeerDetails)[:zgensym_d4b91a75c2094c05_26]
				} else {
					z.SerzPeerDetails = make([]*PeerDetail, zgensym_d4b91a75c2094c05_26)
				}
				for zgensym_d4b91a75c2094c05_12 := range z.SerzPeerDetails {
					// unmarshalGen.gPtr(): we have a BaseElem.

					// unmarshalGen.gPtr(): we have an IDENT:

					if nbs.AlwaysNil {
						if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] != nil {
							z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].UnmarshalMsg(msgp.OnlyNilSlice)
						}
					} else {
						// not nbs.AlwaysNil
						if msgp.IsNil(bts) {
							bts = bts[1:]
							if nil != z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] {
								z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].UnmarshalMsg(msgp.OnlyNilSlice)
							}
						} else {
							// not nbs.AlwaysNil and not IsNil(bts): have something to read

							if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] == nil {
								z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] = new(PeerDetail)
							}

							bts, err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].UnmarshalMsg(bts)
							if err != nil {
								return
							}
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss22zgensym_d4b91a75c2094c05_23 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of ReliableMembershipList
var unmarshalMsgFieldOrder22zgensym_d4b91a75c2094c05_23 = []string{"CzarName_zid00_str", "Vers_zid01_rct", "SerzPeerDetails_zid02_slc", ""}

var unmarshalMsgFieldSkip22zgensym_d4b91a75c2094c05_23 = []bool{false, false, false, true}

// fields of RMVersionTuple
var unmarshalMsgFieldOrder24zgensym_d4b91a75c2094c05_25 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var unmarshalMsgFieldSkip24zgensym_d4b91a75c2094c05_25 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ReliableMembershipList) Msgsize() (s int) {
	s = 1 + 19 + msgp.StringPrefixSize + len(z.CzarName) + 15 + 1 + 25 + msgp.Int64Size + 18 + msgp.Int64Size + 29 + msgp.Int64Size + 26 + msgp.ArrayHeaderSize
	for zgensym_d4b91a75c2094c05_12 := range z.SerzPeerDetails {
		if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12] == nil {
			s += msgp.NilSize
		} else {
			s += z.SerzPeerDetails[zgensym_d4b91a75c2094c05_12].Msgsize()
		}
	}
	return
}
func (z *ReliableMembershipList) Gstring() (r string) {
	r = "&ReliableMembershipList{\n"
	r += fmt.Sprintf("       CzarName: \"%v\",\n", z.CzarName)
	r += fmt.Sprintf("           Vers: %v,\n", z.Vers)
	r += fmt.Sprintf("SerzPeerDetails: %v,\n", z.SerzPeerDetails)
	r += "}\n"
	return
}
