// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package tube

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Czar) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields0zgensym_d4b91a75c2094c05_1 = 3

	// -- templateDecodeMsg starts here--
	var totalEncodedFields0zgensym_d4b91a75c2094c05_1 uint32
	totalEncodedFields0zgensym_d4b91a75c2094c05_1, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft0zgensym_d4b91a75c2094c05_1 := totalEncodedFields0zgensym_d4b91a75c2094c05_1
	missingFieldsLeft0zgensym_d4b91a75c2094c05_1 := maxFields0zgensym_d4b91a75c2094c05_1 - totalEncodedFields0zgensym_d4b91a75c2094c05_1

	var nextMiss0zgensym_d4b91a75c2094c05_1 int32 = -1
	var found0zgensym_d4b91a75c2094c05_1 [maxFields0zgensym_d4b91a75c2094c05_1]bool
	var curField0zgensym_d4b91a75c2094c05_1 string

doneWithStruct0zgensym_d4b91a75c2094c05_1:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft0zgensym_d4b91a75c2094c05_1 > 0 || missingFieldsLeft0zgensym_d4b91a75c2094c05_1 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft0zgensym_d4b91a75c2094c05_1, missingFieldsLeft0zgensym_d4b91a75c2094c05_1, msgp.ShowFound(found0zgensym_d4b91a75c2094c05_1[:]), decodeMsgFieldOrder0zgensym_d4b91a75c2094c05_1)
		if encodedFieldsLeft0zgensym_d4b91a75c2094c05_1 > 0 {
			encodedFieldsLeft0zgensym_d4b91a75c2094c05_1--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField0zgensym_d4b91a75c2094c05_1 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss0zgensym_d4b91a75c2094c05_1 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss0zgensym_d4b91a75c2094c05_1 = 0
			}
			for nextMiss0zgensym_d4b91a75c2094c05_1 < maxFields0zgensym_d4b91a75c2094c05_1 && (found0zgensym_d4b91a75c2094c05_1[nextMiss0zgensym_d4b91a75c2094c05_1] || decodeMsgFieldSkip0zgensym_d4b91a75c2094c05_1[nextMiss0zgensym_d4b91a75c2094c05_1]) {
				nextMiss0zgensym_d4b91a75c2094c05_1++
			}
			if nextMiss0zgensym_d4b91a75c2094c05_1 == maxFields0zgensym_d4b91a75c2094c05_1 {
				// filled all the empty fields!
				break doneWithStruct0zgensym_d4b91a75c2094c05_1
			}
			missingFieldsLeft0zgensym_d4b91a75c2094c05_1--
			curField0zgensym_d4b91a75c2094c05_1 = decodeMsgFieldOrder0zgensym_d4b91a75c2094c05_1[nextMiss0zgensym_d4b91a75c2094c05_1]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField0zgensym_d4b91a75c2094c05_1)
		switch curField0zgensym_d4b91a75c2094c05_1 {
		// -- templateDecodeMsg ends here --

		case "TubeCliName_zid00_str":
			found0zgensym_d4b91a75c2094c05_1[0] = true
			z.TubeCliName, err = dc.ReadString()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss0zgensym_d4b91a75c2094c05_1 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Czar
var decodeMsgFieldOrder0zgensym_d4b91a75c2094c05_1 = []string{"TubeCliName_zid00_str", "", ""}

var decodeMsgFieldSkip0zgensym_d4b91a75c2094c05_1 = []bool{false, true, true}

// fieldsNotEmpty supports omitempty tags
func (z *Czar) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 1
	}
	var fieldsInUse uint32 = 1
	isempty[0] = (len(z.TubeCliName) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Czar) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_2 [3]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_3 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_2[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_3 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Czar'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x43, 0x7a, 0x61, 0x72})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_2[0] {
		// write "TubeCliName_zid00_str"
		err = en.Append(0xb5, 0x54, 0x75, 0x62, 0x65, 0x43, 0x6c, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.TubeCliName)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Czar) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "TubeCliName_zid00_str"
		o = append(o, 0xb5, 0x54, 0x75, 0x62, 0x65, 0x43, 0x6c, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.TubeCliName)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Czar) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Czar) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields4zgensym_d4b91a75c2094c05_5 = 3

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields4zgensym_d4b91a75c2094c05_5 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields4zgensym_d4b91a75c2094c05_5, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft4zgensym_d4b91a75c2094c05_5 := totalEncodedFields4zgensym_d4b91a75c2094c05_5
	missingFieldsLeft4zgensym_d4b91a75c2094c05_5 := maxFields4zgensym_d4b91a75c2094c05_5 - totalEncodedFields4zgensym_d4b91a75c2094c05_5

	var nextMiss4zgensym_d4b91a75c2094c05_5 int32 = -1
	var found4zgensym_d4b91a75c2094c05_5 [maxFields4zgensym_d4b91a75c2094c05_5]bool
	var curField4zgensym_d4b91a75c2094c05_5 string

doneWithStruct4zgensym_d4b91a75c2094c05_5:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft4zgensym_d4b91a75c2094c05_5 > 0 || missingFieldsLeft4zgensym_d4b91a75c2094c05_5 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft4zgensym_d4b91a75c2094c05_5, missingFieldsLeft4zgensym_d4b91a75c2094c05_5, msgp.ShowFound(found4zgensym_d4b91a75c2094c05_5[:]), unmarshalMsgFieldOrder4zgensym_d4b91a75c2094c05_5)
		if encodedFieldsLeft4zgensym_d4b91a75c2094c05_5 > 0 {
			encodedFieldsLeft4zgensym_d4b91a75c2094c05_5--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField4zgensym_d4b91a75c2094c05_5 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss4zgensym_d4b91a75c2094c05_5 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss4zgensym_d4b91a75c2094c05_5 = 0
			}
			for nextMiss4zgensym_d4b91a75c2094c05_5 < maxFields4zgensym_d4b91a75c2094c05_5 && (found4zgensym_d4b91a75c2094c05_5[nextMiss4zgensym_d4b91a75c2094c05_5] || unmarshalMsgFieldSkip4zgensym_d4b91a75c2094c05_5[nextMiss4zgensym_d4b91a75c2094c05_5]) {
				nextMiss4zgensym_d4b91a75c2094c05_5++
			}
			if nextMiss4zgensym_d4b91a75c2094c05_5 == maxFields4zgensym_d4b91a75c2094c05_5 {
				// filled all the empty fields!
				break doneWithStruct4zgensym_d4b91a75c2094c05_5
			}
			missingFieldsLeft4zgensym_d4b91a75c2094c05_5--
			curField4zgensym_d4b91a75c2094c05_5 = unmarshalMsgFieldOrder4zgensym_d4b91a75c2094c05_5[nextMiss4zgensym_d4b91a75c2094c05_5]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField4zgensym_d4b91a75c2094c05_5)
		switch curField4zgensym_d4b91a75c2094c05_5 {
		// -- templateUnmarshalMsg ends here --

		case "TubeCliName_zid00_str":
			found4zgensym_d4b91a75c2094c05_5[0] = true
			z.TubeCliName, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss4zgensym_d4b91a75c2094c05_5 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Czar
var unmarshalMsgFieldOrder4zgensym_d4b91a75c2094c05_5 = []string{"TubeCliName_zid00_str", "", ""}

var unmarshalMsgFieldSkip4zgensym_d4b91a75c2094c05_5 = []bool{false, true, true}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Czar) Msgsize() (s int) {
	s = 1 + 22 + msgp.StringPrefixSize + len(z.TubeCliName)
	return
}
func (z *Czar) Gstring() (r string) {
	r = "&Czar{\n"
	r += fmt.Sprintf("TubeCliName: \"%v\",\n", z.TubeCliName)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *PeerDetailPlus) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields6zgensym_d4b91a75c2094c05_7 = 3

	// -- templateDecodeMsg starts here--
	var totalEncodedFields6zgensym_d4b91a75c2094c05_7 uint32
	totalEncodedFields6zgensym_d4b91a75c2094c05_7, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft6zgensym_d4b91a75c2094c05_7 := totalEncodedFields6zgensym_d4b91a75c2094c05_7
	missingFieldsLeft6zgensym_d4b91a75c2094c05_7 := maxFields6zgensym_d4b91a75c2094c05_7 - totalEncodedFields6zgensym_d4b91a75c2094c05_7

	var nextMiss6zgensym_d4b91a75c2094c05_7 int32 = -1
	var found6zgensym_d4b91a75c2094c05_7 [maxFields6zgensym_d4b91a75c2094c05_7]bool
	var curField6zgensym_d4b91a75c2094c05_7 string

doneWithStruct6zgensym_d4b91a75c2094c05_7:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft6zgensym_d4b91a75c2094c05_7 > 0 || missingFieldsLeft6zgensym_d4b91a75c2094c05_7 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft6zgensym_d4b91a75c2094c05_7, missingFieldsLeft6zgensym_d4b91a75c2094c05_7, msgp.ShowFound(found6zgensym_d4b91a75c2094c05_7[:]), decodeMsgFieldOrder6zgensym_d4b91a75c2094c05_7)
		if encodedFieldsLeft6zgensym_d4b91a75c2094c05_7 > 0 {
			encodedFieldsLeft6zgensym_d4b91a75c2094c05_7--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField6zgensym_d4b91a75c2094c05_7 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss6zgensym_d4b91a75c2094c05_7 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss6zgensym_d4b91a75c2094c05_7 = 0
			}
			for nextMiss6zgensym_d4b91a75c2094c05_7 < maxFields6zgensym_d4b91a75c2094c05_7 && (found6zgensym_d4b91a75c2094c05_7[nextMiss6zgensym_d4b91a75c2094c05_7] || decodeMsgFieldSkip6zgensym_d4b91a75c2094c05_7[nextMiss6zgensym_d4b91a75c2094c05_7]) {
				nextMiss6zgensym_d4b91a75c2094c05_7++
			}
			if nextMiss6zgensym_d4b91a75c2094c05_7 == maxFields6zgensym_d4b91a75c2094c05_7 {
				// filled all the empty fields!
				break doneWithStruct6zgensym_d4b91a75c2094c05_7
			}
			missingFieldsLeft6zgensym_d4b91a75c2094c05_7--
			curField6zgensym_d4b91a75c2094c05_7 = decodeMsgFieldOrder6zgensym_d4b91a75c2094c05_7[nextMiss6zgensym_d4b91a75c2094c05_7]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField6zgensym_d4b91a75c2094c05_7)
		switch curField6zgensym_d4b91a75c2094c05_7 {
		// -- templateDecodeMsg ends here --

		case "Det_zid00_ptr":
			found6zgensym_d4b91a75c2094c05_7[0] = true
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}

				if z.Det != nil {
					dc.PushAlwaysNil()
					err = z.Det.DecodeMsg(dc)
					if err != nil {
						return
					}
					dc.PopAlwaysNil()
				}
			} else {
				// not Nil, we have something to read

				if z.Det == nil {
					z.Det = new(PeerDetail)
				}
				dc.DedupIndexEachPtr(z.Det)

				err = z.Det.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		case "RMemberLeaseUntilTm_zid01_tim":
			found6zgensym_d4b91a75c2094c05_7[1] = true
			z.RMemberLeaseUntilTm, err = dc.ReadTime()
			if err != nil {
				return
			}
		case "RMemberLeaseDur_zid02_dur":
			found6zgensym_d4b91a75c2094c05_7[2] = true
			z.RMemberLeaseDur, err = dc.ReadDuration()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss6zgensym_d4b91a75c2094c05_7 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of PeerDetailPlus
var decodeMsgFieldOrder6zgensym_d4b91a75c2094c05_7 = []string{"Det_zid00_ptr", "RMemberLeaseUntilTm_zid01_tim", "RMemberLeaseDur_zid02_dur"}

var decodeMsgFieldSkip6zgensym_d4b91a75c2094c05_7 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *PeerDetailPlus) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 3
	}
	var fieldsInUse uint32 = 3
	isempty[0] = (z.Det == nil) // pointer, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.RMemberLeaseUntilTm.IsZero()) // time.Time, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = false
	if isempty[2] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *PeerDetailPlus) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_8 [3]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_9 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_8[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_9 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'PeerDetailPlus'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x50, 0x65, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x75, 0x73})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_8[0] {
		// write "Det_zid00_ptr"
		err = en.Append(0xad, 0x44, 0x65, 0x74, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x70, 0x74, 0x72)
		if err != nil {
			return err
		}
		// gPtr.encodeGen():

		if z.Det == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Det.EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_8[1] {
		// write "RMemberLeaseUntilTm_zid01_tim"
		err = en.Append(0xbd, 0x52, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x54, 0x6d, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x74, 0x69, 0x6d)
		if err != nil {
			return err
		}
		err = en.WriteTime(z.RMemberLeaseUntilTm)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_8[2] {
		// write "RMemberLeaseDur_zid02_dur"
		err = en.Append(0xb9, 0x52, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x75, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x64, 0x75, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteDuration(z.RMemberLeaseDur)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PeerDetailPlus) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Det_zid00_ptr"
		o = append(o, 0xad, 0x44, 0x65, 0x74, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x70, 0x74, 0x72)
		// marshalGen.gPtr()

		if z.Det == nil {
			o = msgp.AppendNil(o)
		} else {
			// hmm.. no en, no place to check en.DedupWriteIsDup(z)

			o, err = z.Det.MarshalMsg(o) // not is.iface
			if err != nil {
				return
			}
		}
	}

	if !empty[1] {
		// string "RMemberLeaseUntilTm_zid01_tim"
		o = append(o, 0xbd, 0x52, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x54, 0x6d, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x74, 0x69, 0x6d)
		o = msgp.AppendTime(o, z.RMemberLeaseUntilTm)
	}

	if !empty[2] {
		// string "RMemberLeaseDur_zid02_dur"
		o = append(o, 0xb9, 0x52, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x75, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x64, 0x75, 0x72)
		o = msgp.AppendDuration(o, z.RMemberLeaseDur)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PeerDetailPlus) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *PeerDetailPlus) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields10zgensym_d4b91a75c2094c05_11 = 3

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields10zgensym_d4b91a75c2094c05_11 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields10zgensym_d4b91a75c2094c05_11, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft10zgensym_d4b91a75c2094c05_11 := totalEncodedFields10zgensym_d4b91a75c2094c05_11
	missingFieldsLeft10zgensym_d4b91a75c2094c05_11 := maxFields10zgensym_d4b91a75c2094c05_11 - totalEncodedFields10zgensym_d4b91a75c2094c05_11

	var nextMiss10zgensym_d4b91a75c2094c05_11 int32 = -1
	var found10zgensym_d4b91a75c2094c05_11 [maxFields10zgensym_d4b91a75c2094c05_11]bool
	var curField10zgensym_d4b91a75c2094c05_11 string

doneWithStruct10zgensym_d4b91a75c2094c05_11:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft10zgensym_d4b91a75c2094c05_11 > 0 || missingFieldsLeft10zgensym_d4b91a75c2094c05_11 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft10zgensym_d4b91a75c2094c05_11, missingFieldsLeft10zgensym_d4b91a75c2094c05_11, msgp.ShowFound(found10zgensym_d4b91a75c2094c05_11[:]), unmarshalMsgFieldOrder10zgensym_d4b91a75c2094c05_11)
		if encodedFieldsLeft10zgensym_d4b91a75c2094c05_11 > 0 {
			encodedFieldsLeft10zgensym_d4b91a75c2094c05_11--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField10zgensym_d4b91a75c2094c05_11 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss10zgensym_d4b91a75c2094c05_11 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss10zgensym_d4b91a75c2094c05_11 = 0
			}
			for nextMiss10zgensym_d4b91a75c2094c05_11 < maxFields10zgensym_d4b91a75c2094c05_11 && (found10zgensym_d4b91a75c2094c05_11[nextMiss10zgensym_d4b91a75c2094c05_11] || unmarshalMsgFieldSkip10zgensym_d4b91a75c2094c05_11[nextMiss10zgensym_d4b91a75c2094c05_11]) {
				nextMiss10zgensym_d4b91a75c2094c05_11++
			}
			if nextMiss10zgensym_d4b91a75c2094c05_11 == maxFields10zgensym_d4b91a75c2094c05_11 {
				// filled all the empty fields!
				break doneWithStruct10zgensym_d4b91a75c2094c05_11
			}
			missingFieldsLeft10zgensym_d4b91a75c2094c05_11--
			curField10zgensym_d4b91a75c2094c05_11 = unmarshalMsgFieldOrder10zgensym_d4b91a75c2094c05_11[nextMiss10zgensym_d4b91a75c2094c05_11]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField10zgensym_d4b91a75c2094c05_11)
		switch curField10zgensym_d4b91a75c2094c05_11 {
		// -- templateUnmarshalMsg ends here --

		case "Det_zid00_ptr":
			found10zgensym_d4b91a75c2094c05_11[0] = true
			// unmarshalGen.gPtr(): we have a BaseElem.

			// unmarshalGen.gPtr(): we have an IDENT:

			if nbs.AlwaysNil {
				if z.Det != nil {
					z.Det.UnmarshalMsg(msgp.OnlyNilSlice)
				}
			} else {
				// not nbs.AlwaysNil
				if msgp.IsNil(bts) {
					bts = bts[1:]
					if nil != z.Det {
						z.Det.UnmarshalMsg(msgp.OnlyNilSlice)
					}
				} else {
					// not nbs.AlwaysNil and not IsNil(bts): have something to read

					if z.Det == nil {
						z.Det = new(PeerDetail)
					}

					bts, err = z.Det.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		case "RMemberLeaseUntilTm_zid01_tim":
			found10zgensym_d4b91a75c2094c05_11[1] = true
			z.RMemberLeaseUntilTm, bts, err = nbs.ReadTimeBytes(bts)

			if err != nil {
				return
			}
		case "RMemberLeaseDur_zid02_dur":
			found10zgensym_d4b91a75c2094c05_11[2] = true
			z.RMemberLeaseDur, bts, err = nbs.ReadDurationBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss10zgensym_d4b91a75c2094c05_11 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of PeerDetailPlus
var unmarshalMsgFieldOrder10zgensym_d4b91a75c2094c05_11 = []string{"Det_zid00_ptr", "RMemberLeaseUntilTm_zid01_tim", "RMemberLeaseDur_zid02_dur"}

var unmarshalMsgFieldSkip10zgensym_d4b91a75c2094c05_11 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PeerDetailPlus) Msgsize() (s int) {
	s = 1 + 14
	if z.Det == nil {
		s += msgp.NilSize
	} else {
		s += z.Det.Msgsize()
	}
	s += 30 + msgp.TimeSize + 26 + msgp.DurationSize
	return
}
func (z *PeerDetailPlus) Gstring() (r string) {
	r = "&PeerDetailPlus{\n"
	r += fmt.Sprintf("                Det: %v,\n", z.Det)
	r += fmt.Sprintf("RMemberLeaseUntilTm: %v,\n", z.RMemberLeaseUntilTm)
	r += fmt.Sprintf("    RMemberLeaseDur: %v,\n", z.RMemberLeaseDur)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *RMVersionTuple) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields12zgensym_d4b91a75c2094c05_13 = 3

	// -- templateDecodeMsg starts here--
	var totalEncodedFields12zgensym_d4b91a75c2094c05_13 uint32
	totalEncodedFields12zgensym_d4b91a75c2094c05_13, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft12zgensym_d4b91a75c2094c05_13 := totalEncodedFields12zgensym_d4b91a75c2094c05_13
	missingFieldsLeft12zgensym_d4b91a75c2094c05_13 := maxFields12zgensym_d4b91a75c2094c05_13 - totalEncodedFields12zgensym_d4b91a75c2094c05_13

	var nextMiss12zgensym_d4b91a75c2094c05_13 int32 = -1
	var found12zgensym_d4b91a75c2094c05_13 [maxFields12zgensym_d4b91a75c2094c05_13]bool
	var curField12zgensym_d4b91a75c2094c05_13 string

doneWithStruct12zgensym_d4b91a75c2094c05_13:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft12zgensym_d4b91a75c2094c05_13 > 0 || missingFieldsLeft12zgensym_d4b91a75c2094c05_13 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft12zgensym_d4b91a75c2094c05_13, missingFieldsLeft12zgensym_d4b91a75c2094c05_13, msgp.ShowFound(found12zgensym_d4b91a75c2094c05_13[:]), decodeMsgFieldOrder12zgensym_d4b91a75c2094c05_13)
		if encodedFieldsLeft12zgensym_d4b91a75c2094c05_13 > 0 {
			encodedFieldsLeft12zgensym_d4b91a75c2094c05_13--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField12zgensym_d4b91a75c2094c05_13 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss12zgensym_d4b91a75c2094c05_13 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss12zgensym_d4b91a75c2094c05_13 = 0
			}
			for nextMiss12zgensym_d4b91a75c2094c05_13 < maxFields12zgensym_d4b91a75c2094c05_13 && (found12zgensym_d4b91a75c2094c05_13[nextMiss12zgensym_d4b91a75c2094c05_13] || decodeMsgFieldSkip12zgensym_d4b91a75c2094c05_13[nextMiss12zgensym_d4b91a75c2094c05_13]) {
				nextMiss12zgensym_d4b91a75c2094c05_13++
			}
			if nextMiss12zgensym_d4b91a75c2094c05_13 == maxFields12zgensym_d4b91a75c2094c05_13 {
				// filled all the empty fields!
				break doneWithStruct12zgensym_d4b91a75c2094c05_13
			}
			missingFieldsLeft12zgensym_d4b91a75c2094c05_13--
			curField12zgensym_d4b91a75c2094c05_13 = decodeMsgFieldOrder12zgensym_d4b91a75c2094c05_13[nextMiss12zgensym_d4b91a75c2094c05_13]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField12zgensym_d4b91a75c2094c05_13)
		switch curField12zgensym_d4b91a75c2094c05_13 {
		// -- templateDecodeMsg ends here --

		case "CzarLeaseEpoch_zid00_i64":
			found12zgensym_d4b91a75c2094c05_13[0] = true
			z.CzarLeaseEpoch, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "Version_zid01_i64":
			found12zgensym_d4b91a75c2094c05_13[1] = true
			z.Version, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "LeaseUpdateCounter_zid02_i64":
			found12zgensym_d4b91a75c2094c05_13[2] = true
			z.LeaseUpdateCounter, err = dc.ReadInt64()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss12zgensym_d4b91a75c2094c05_13 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of RMVersionTuple
var decodeMsgFieldOrder12zgensym_d4b91a75c2094c05_13 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var decodeMsgFieldSkip12zgensym_d4b91a75c2094c05_13 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *RMVersionTuple) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 3
	}
	var fieldsInUse uint32 = 3
	isempty[0] = (z.CzarLeaseEpoch == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.Version == 0) // number, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.LeaseUpdateCounter == 0) // number, omitempty
	if isempty[2] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *RMVersionTuple) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_14 [3]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_15 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_14[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_15 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'RMVersionTuple'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x52, 0x4d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_14[0] {
		// write "CzarLeaseEpoch_zid00_i64"
		err = en.Append(0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.CzarLeaseEpoch)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_14[1] {
		// write "Version_zid01_i64"
		err = en.Append(0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.Version)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_14[2] {
		// write "LeaseUpdateCounter_zid02_i64"
		err = en.Append(0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.LeaseUpdateCounter)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RMVersionTuple) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "CzarLeaseEpoch_zid00_i64"
		o = append(o, 0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.CzarLeaseEpoch)
	}

	if !empty[1] {
		// string "Version_zid01_i64"
		o = append(o, 0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.Version)
	}

	if !empty[2] {
		// string "LeaseUpdateCounter_zid02_i64"
		o = append(o, 0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.LeaseUpdateCounter)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RMVersionTuple) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *RMVersionTuple) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields16zgensym_d4b91a75c2094c05_17 = 3

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields16zgensym_d4b91a75c2094c05_17 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields16zgensym_d4b91a75c2094c05_17, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft16zgensym_d4b91a75c2094c05_17 := totalEncodedFields16zgensym_d4b91a75c2094c05_17
	missingFieldsLeft16zgensym_d4b91a75c2094c05_17 := maxFields16zgensym_d4b91a75c2094c05_17 - totalEncodedFields16zgensym_d4b91a75c2094c05_17

	var nextMiss16zgensym_d4b91a75c2094c05_17 int32 = -1
	var found16zgensym_d4b91a75c2094c05_17 [maxFields16zgensym_d4b91a75c2094c05_17]bool
	var curField16zgensym_d4b91a75c2094c05_17 string

doneWithStruct16zgensym_d4b91a75c2094c05_17:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft16zgensym_d4b91a75c2094c05_17 > 0 || missingFieldsLeft16zgensym_d4b91a75c2094c05_17 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft16zgensym_d4b91a75c2094c05_17, missingFieldsLeft16zgensym_d4b91a75c2094c05_17, msgp.ShowFound(found16zgensym_d4b91a75c2094c05_17[:]), unmarshalMsgFieldOrder16zgensym_d4b91a75c2094c05_17)
		if encodedFieldsLeft16zgensym_d4b91a75c2094c05_17 > 0 {
			encodedFieldsLeft16zgensym_d4b91a75c2094c05_17--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField16zgensym_d4b91a75c2094c05_17 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss16zgensym_d4b91a75c2094c05_17 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss16zgensym_d4b91a75c2094c05_17 = 0
			}
			for nextMiss16zgensym_d4b91a75c2094c05_17 < maxFields16zgensym_d4b91a75c2094c05_17 && (found16zgensym_d4b91a75c2094c05_17[nextMiss16zgensym_d4b91a75c2094c05_17] || unmarshalMsgFieldSkip16zgensym_d4b91a75c2094c05_17[nextMiss16zgensym_d4b91a75c2094c05_17]) {
				nextMiss16zgensym_d4b91a75c2094c05_17++
			}
			if nextMiss16zgensym_d4b91a75c2094c05_17 == maxFields16zgensym_d4b91a75c2094c05_17 {
				// filled all the empty fields!
				break doneWithStruct16zgensym_d4b91a75c2094c05_17
			}
			missingFieldsLeft16zgensym_d4b91a75c2094c05_17--
			curField16zgensym_d4b91a75c2094c05_17 = unmarshalMsgFieldOrder16zgensym_d4b91a75c2094c05_17[nextMiss16zgensym_d4b91a75c2094c05_17]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField16zgensym_d4b91a75c2094c05_17)
		switch curField16zgensym_d4b91a75c2094c05_17 {
		// -- templateUnmarshalMsg ends here --

		case "CzarLeaseEpoch_zid00_i64":
			found16zgensym_d4b91a75c2094c05_17[0] = true
			z.CzarLeaseEpoch, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "Version_zid01_i64":
			found16zgensym_d4b91a75c2094c05_17[1] = true
			z.Version, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "LeaseUpdateCounter_zid02_i64":
			found16zgensym_d4b91a75c2094c05_17[2] = true
			z.LeaseUpdateCounter, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss16zgensym_d4b91a75c2094c05_17 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of RMVersionTuple
var unmarshalMsgFieldOrder16zgensym_d4b91a75c2094c05_17 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var unmarshalMsgFieldSkip16zgensym_d4b91a75c2094c05_17 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RMVersionTuple) Msgsize() (s int) {
	s = 1 + 25 + msgp.Int64Size + 18 + msgp.Int64Size + 29 + msgp.Int64Size
	return
}
func (z *RMVersionTuple) Gstring() (r string) {
	r = "&RMVersionTuple{\n"
	r += fmt.Sprintf("    CzarLeaseEpoch: %v,\n", z.CzarLeaseEpoch)
	r += fmt.Sprintf("           Version: %v,\n", z.Version)
	r += fmt.Sprintf("LeaseUpdateCounter: %v,\n", z.LeaseUpdateCounter)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *ReliableMembershipList) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields19zgensym_d4b91a75c2094c05_20 = 5

	// -- templateDecodeMsg starts here--
	var totalEncodedFields19zgensym_d4b91a75c2094c05_20 uint32
	totalEncodedFields19zgensym_d4b91a75c2094c05_20, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft19zgensym_d4b91a75c2094c05_20 := totalEncodedFields19zgensym_d4b91a75c2094c05_20
	missingFieldsLeft19zgensym_d4b91a75c2094c05_20 := maxFields19zgensym_d4b91a75c2094c05_20 - totalEncodedFields19zgensym_d4b91a75c2094c05_20

	var nextMiss19zgensym_d4b91a75c2094c05_20 int32 = -1
	var found19zgensym_d4b91a75c2094c05_20 [maxFields19zgensym_d4b91a75c2094c05_20]bool
	var curField19zgensym_d4b91a75c2094c05_20 string

doneWithStruct19zgensym_d4b91a75c2094c05_20:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft19zgensym_d4b91a75c2094c05_20 > 0 || missingFieldsLeft19zgensym_d4b91a75c2094c05_20 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft19zgensym_d4b91a75c2094c05_20, missingFieldsLeft19zgensym_d4b91a75c2094c05_20, msgp.ShowFound(found19zgensym_d4b91a75c2094c05_20[:]), decodeMsgFieldOrder19zgensym_d4b91a75c2094c05_20)
		if encodedFieldsLeft19zgensym_d4b91a75c2094c05_20 > 0 {
			encodedFieldsLeft19zgensym_d4b91a75c2094c05_20--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField19zgensym_d4b91a75c2094c05_20 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss19zgensym_d4b91a75c2094c05_20 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss19zgensym_d4b91a75c2094c05_20 = 0
			}
			for nextMiss19zgensym_d4b91a75c2094c05_20 < maxFields19zgensym_d4b91a75c2094c05_20 && (found19zgensym_d4b91a75c2094c05_20[nextMiss19zgensym_d4b91a75c2094c05_20] || decodeMsgFieldSkip19zgensym_d4b91a75c2094c05_20[nextMiss19zgensym_d4b91a75c2094c05_20]) {
				nextMiss19zgensym_d4b91a75c2094c05_20++
			}
			if nextMiss19zgensym_d4b91a75c2094c05_20 == maxFields19zgensym_d4b91a75c2094c05_20 {
				// filled all the empty fields!
				break doneWithStruct19zgensym_d4b91a75c2094c05_20
			}
			missingFieldsLeft19zgensym_d4b91a75c2094c05_20--
			curField19zgensym_d4b91a75c2094c05_20 = decodeMsgFieldOrder19zgensym_d4b91a75c2094c05_20[nextMiss19zgensym_d4b91a75c2094c05_20]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField19zgensym_d4b91a75c2094c05_20)
		switch curField19zgensym_d4b91a75c2094c05_20 {
		// -- templateDecodeMsg ends here --

		case "CzarName_zid00_str":
			found19zgensym_d4b91a75c2094c05_20[0] = true
			z.CzarName, err = dc.ReadString()
			if err != nil {
				return
			}
		case "Vers_zid01_rct":
			found19zgensym_d4b91a75c2094c05_20[1] = true
			const maxFields21zgensym_d4b91a75c2094c05_22 = 3

			// -- templateDecodeMsg starts here--
			var totalEncodedFields21zgensym_d4b91a75c2094c05_22 uint32
			totalEncodedFields21zgensym_d4b91a75c2094c05_22, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			encodedFieldsLeft21zgensym_d4b91a75c2094c05_22 := totalEncodedFields21zgensym_d4b91a75c2094c05_22
			missingFieldsLeft21zgensym_d4b91a75c2094c05_22 := maxFields21zgensym_d4b91a75c2094c05_22 - totalEncodedFields21zgensym_d4b91a75c2094c05_22

			var nextMiss21zgensym_d4b91a75c2094c05_22 int32 = -1
			var found21zgensym_d4b91a75c2094c05_22 [maxFields21zgensym_d4b91a75c2094c05_22]bool
			var curField21zgensym_d4b91a75c2094c05_22 string

		doneWithStruct21zgensym_d4b91a75c2094c05_22:
			// First fill all the encoded fields, then
			// treat the remaining, missing fields, as Nil.
			for encodedFieldsLeft21zgensym_d4b91a75c2094c05_22 > 0 || missingFieldsLeft21zgensym_d4b91a75c2094c05_22 > 0 {
				//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft21zgensym_d4b91a75c2094c05_22, missingFieldsLeft21zgensym_d4b91a75c2094c05_22, msgp.ShowFound(found21zgensym_d4b91a75c2094c05_22[:]), decodeMsgFieldOrder21zgensym_d4b91a75c2094c05_22)
				if encodedFieldsLeft21zgensym_d4b91a75c2094c05_22 > 0 {
					encodedFieldsLeft21zgensym_d4b91a75c2094c05_22--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						return
					}
					curField21zgensym_d4b91a75c2094c05_22 = msgp.UnsafeString(field)
				} else {
					//missing fields need handling
					if nextMiss21zgensym_d4b91a75c2094c05_22 < 0 {
						// tell the reader to only give us Nils
						// until further notice.
						dc.PushAlwaysNil()
						nextMiss21zgensym_d4b91a75c2094c05_22 = 0
					}
					for nextMiss21zgensym_d4b91a75c2094c05_22 < maxFields21zgensym_d4b91a75c2094c05_22 && (found21zgensym_d4b91a75c2094c05_22[nextMiss21zgensym_d4b91a75c2094c05_22] || decodeMsgFieldSkip21zgensym_d4b91a75c2094c05_22[nextMiss21zgensym_d4b91a75c2094c05_22]) {
						nextMiss21zgensym_d4b91a75c2094c05_22++
					}
					if nextMiss21zgensym_d4b91a75c2094c05_22 == maxFields21zgensym_d4b91a75c2094c05_22 {
						// filled all the empty fields!
						break doneWithStruct21zgensym_d4b91a75c2094c05_22
					}
					missingFieldsLeft21zgensym_d4b91a75c2094c05_22--
					curField21zgensym_d4b91a75c2094c05_22 = decodeMsgFieldOrder21zgensym_d4b91a75c2094c05_22[nextMiss21zgensym_d4b91a75c2094c05_22]
				}
				//fmt.Printf("switching on curField: '%v'\n", curField21zgensym_d4b91a75c2094c05_22)
				switch curField21zgensym_d4b91a75c2094c05_22 {
				// -- templateDecodeMsg ends here --

				case "CzarLeaseEpoch_zid00_i64":
					found21zgensym_d4b91a75c2094c05_22[0] = true
					z.Vers.CzarLeaseEpoch, err = dc.ReadInt64()
					if err != nil {
						return
					}
				case "Version_zid01_i64":
					found21zgensym_d4b91a75c2094c05_22[1] = true
					z.Vers.Version, err = dc.ReadInt64()
					if err != nil {
						return
					}
				case "LeaseUpdateCounter_zid02_i64":
					found21zgensym_d4b91a75c2094c05_22[2] = true
					z.Vers.LeaseUpdateCounter, err = dc.ReadInt64()
					if err != nil {
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						return
					}
				}
			}
			if nextMiss21zgensym_d4b91a75c2094c05_22 != -1 {
				dc.PopAlwaysNil()
			}

		case "SerzPeerDetails_zid02_slc":
			found19zgensym_d4b91a75c2094c05_20[2] = true
			var zgensym_d4b91a75c2094c05_23 uint32
			zgensym_d4b91a75c2094c05_23, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.SerzPeerDetails) >= int(zgensym_d4b91a75c2094c05_23) {
				z.SerzPeerDetails = (z.SerzPeerDetails)[:zgensym_d4b91a75c2094c05_23]
			} else {
				z.SerzPeerDetails = make([]*PeerDetailPlus, zgensym_d4b91a75c2094c05_23)
			}
			for zgensym_d4b91a75c2094c05_18 := range z.SerzPeerDetails {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}

					if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] != nil {
						dc.PushAlwaysNil()
						err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].DecodeMsg(dc)
						if err != nil {
							return
						}
						dc.PopAlwaysNil()
					}
				} else {
					// not Nil, we have something to read

					if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] == nil {
						z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] = new(PeerDetailPlus)
					}
					dc.DedupIndexEachPtr(z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18])

					err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].DecodeMsg(dc)
					if err != nil {
						return
					}
				}
			}
		case "MemberLeaseDur_zid03_dur":
			found19zgensym_d4b91a75c2094c05_20[3] = true
			z.MemberLeaseDur, err = dc.ReadDuration()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss19zgensym_d4b91a75c2094c05_20 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of ReliableMembershipList
var decodeMsgFieldOrder19zgensym_d4b91a75c2094c05_20 = []string{"CzarName_zid00_str", "Vers_zid01_rct", "SerzPeerDetails_zid02_slc", "MemberLeaseDur_zid03_dur", ""}

var decodeMsgFieldSkip19zgensym_d4b91a75c2094c05_20 = []bool{false, false, false, false, true}

// fields of RMVersionTuple
var decodeMsgFieldOrder21zgensym_d4b91a75c2094c05_22 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var decodeMsgFieldSkip21zgensym_d4b91a75c2094c05_22 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *ReliableMembershipList) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 4
	}
	var fieldsInUse uint32 = 4
	isempty[0] = (len(z.CzarName) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = false // struct values are never empty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.SerzPeerDetails) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = false
	if isempty[3] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *ReliableMembershipList) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_d4b91a75c2094c05_24 [5]bool
	fieldsInUse_zgensym_d4b91a75c2094c05_25 := z.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_24[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_25 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'ReliableMembershipList'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74})
	if err != nil {
		return err
	}

	if !empty_zgensym_d4b91a75c2094c05_24[0] {
		// write "CzarName_zid00_str"
		err = en.Append(0xb2, 0x43, 0x7a, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.CzarName)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_24[1] {
		// write "Vers_zid01_rct"
		err = en.Append(0xae, 0x56, 0x65, 0x72, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x72, 0x63, 0x74)
		if err != nil {
			return err
		}

		// honor the omitempty tags
		var empty_zgensym_d4b91a75c2094c05_26 [3]bool
		fieldsInUse_zgensym_d4b91a75c2094c05_27 := z.Vers.fieldsNotEmpty(empty_zgensym_d4b91a75c2094c05_26[:])

		// map header
		err = en.WriteMapHeader(fieldsInUse_zgensym_d4b91a75c2094c05_27 + 1)
		if err != nil {
			return err
		}

		// runtime struct type identification for 'RMVersionTuple'
		err = en.Append(0xa1, 0x40)
		if err != nil {
			return err
		}
		err = en.WriteStringFromBytes([]byte{0x52, 0x4d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65})
		if err != nil {
			return err
		}

		if !empty_zgensym_d4b91a75c2094c05_26[0] {
			// write "CzarLeaseEpoch_zid00_i64"
			err = en.Append(0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteInt64(z.Vers.CzarLeaseEpoch)
			if err != nil {
				return
			}
		}

		if !empty_zgensym_d4b91a75c2094c05_26[1] {
			// write "Version_zid01_i64"
			err = en.Append(0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteInt64(z.Vers.Version)
			if err != nil {
				return
			}
		}

		if !empty_zgensym_d4b91a75c2094c05_26[2] {
			// write "LeaseUpdateCounter_zid02_i64"
			err = en.Append(0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteInt64(z.Vers.LeaseUpdateCounter)
			if err != nil {
				return
			}
		}

	}

	if !empty_zgensym_d4b91a75c2094c05_24[2] {
		// write "SerzPeerDetails_zid02_slc"
		err = en.Append(0xb9, 0x53, 0x65, 0x72, 0x7a, 0x50, 0x65, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x6c, 0x63)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.SerzPeerDetails)))
		if err != nil {
			return
		}
		for zgensym_d4b91a75c2094c05_18 := range z.SerzPeerDetails {
			// gPtr.encodeGen():

			if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	if !empty_zgensym_d4b91a75c2094c05_24[3] {
		// write "MemberLeaseDur_zid03_dur"
		err = en.Append(0xb8, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x75, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x64, 0x75, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteDuration(z.MemberLeaseDur)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ReliableMembershipList) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [5]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "CzarName_zid00_str"
		o = append(o, 0xb2, 0x43, 0x7a, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.CzarName)
	}

	if !empty[1] {
		// string "Vers_zid01_rct"
		o = append(o, 0xae, 0x56, 0x65, 0x72, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x72, 0x63, 0x74)

		// honor the omitempty tags
		var empty [3]bool
		fieldsInUse := z.Vers.fieldsNotEmpty(empty[:])
		o = msgp.AppendMapHeader(o, fieldsInUse)

		if !empty[0] {
			// string "CzarLeaseEpoch_zid00_i64"
			o = append(o, 0xb8, 0x43, 0x7a, 0x61, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x36, 0x34)
			o = msgp.AppendInt64(o, z.Vers.CzarLeaseEpoch)
		}

		if !empty[1] {
			// string "Version_zid01_i64"
			o = append(o, 0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x69, 0x36, 0x34)
			o = msgp.AppendInt64(o, z.Vers.Version)
		}

		if !empty[2] {
			// string "LeaseUpdateCounter_zid02_i64"
			o = append(o, 0xbc, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x69, 0x36, 0x34)
			o = msgp.AppendInt64(o, z.Vers.LeaseUpdateCounter)
		}

	}

	if !empty[2] {
		// string "SerzPeerDetails_zid02_slc"
		o = append(o, 0xb9, 0x53, 0x65, 0x72, 0x7a, 0x50, 0x65, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x6c, 0x63)
		o = msgp.AppendArrayHeader(o, uint32(len(z.SerzPeerDetails)))
		for zgensym_d4b91a75c2094c05_18 := range z.SerzPeerDetails {
			// marshalGen.gPtr()

			if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] == nil {
				o = msgp.AppendNil(o)
			} else {
				// hmm.. no en, no place to check en.DedupWriteIsDup(z)

				o, err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].MarshalMsg(o) // not is.iface
				if err != nil {
					return
				}
			}
		}
	}

	if !empty[3] {
		// string "MemberLeaseDur_zid03_dur"
		o = append(o, 0xb8, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x75, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x64, 0x75, 0x72)
		o = msgp.AppendDuration(o, z.MemberLeaseDur)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReliableMembershipList) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *ReliableMembershipList) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields28zgensym_d4b91a75c2094c05_29 = 5

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields28zgensym_d4b91a75c2094c05_29 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields28zgensym_d4b91a75c2094c05_29, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft28zgensym_d4b91a75c2094c05_29 := totalEncodedFields28zgensym_d4b91a75c2094c05_29
	missingFieldsLeft28zgensym_d4b91a75c2094c05_29 := maxFields28zgensym_d4b91a75c2094c05_29 - totalEncodedFields28zgensym_d4b91a75c2094c05_29

	var nextMiss28zgensym_d4b91a75c2094c05_29 int32 = -1
	var found28zgensym_d4b91a75c2094c05_29 [maxFields28zgensym_d4b91a75c2094c05_29]bool
	var curField28zgensym_d4b91a75c2094c05_29 string

doneWithStruct28zgensym_d4b91a75c2094c05_29:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft28zgensym_d4b91a75c2094c05_29 > 0 || missingFieldsLeft28zgensym_d4b91a75c2094c05_29 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft28zgensym_d4b91a75c2094c05_29, missingFieldsLeft28zgensym_d4b91a75c2094c05_29, msgp.ShowFound(found28zgensym_d4b91a75c2094c05_29[:]), unmarshalMsgFieldOrder28zgensym_d4b91a75c2094c05_29)
		if encodedFieldsLeft28zgensym_d4b91a75c2094c05_29 > 0 {
			encodedFieldsLeft28zgensym_d4b91a75c2094c05_29--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField28zgensym_d4b91a75c2094c05_29 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss28zgensym_d4b91a75c2094c05_29 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss28zgensym_d4b91a75c2094c05_29 = 0
			}
			for nextMiss28zgensym_d4b91a75c2094c05_29 < maxFields28zgensym_d4b91a75c2094c05_29 && (found28zgensym_d4b91a75c2094c05_29[nextMiss28zgensym_d4b91a75c2094c05_29] || unmarshalMsgFieldSkip28zgensym_d4b91a75c2094c05_29[nextMiss28zgensym_d4b91a75c2094c05_29]) {
				nextMiss28zgensym_d4b91a75c2094c05_29++
			}
			if nextMiss28zgensym_d4b91a75c2094c05_29 == maxFields28zgensym_d4b91a75c2094c05_29 {
				// filled all the empty fields!
				break doneWithStruct28zgensym_d4b91a75c2094c05_29
			}
			missingFieldsLeft28zgensym_d4b91a75c2094c05_29--
			curField28zgensym_d4b91a75c2094c05_29 = unmarshalMsgFieldOrder28zgensym_d4b91a75c2094c05_29[nextMiss28zgensym_d4b91a75c2094c05_29]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField28zgensym_d4b91a75c2094c05_29)
		switch curField28zgensym_d4b91a75c2094c05_29 {
		// -- templateUnmarshalMsg ends here --

		case "CzarName_zid00_str":
			found28zgensym_d4b91a75c2094c05_29[0] = true
			z.CzarName, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "Vers_zid01_rct":
			found28zgensym_d4b91a75c2094c05_29[1] = true
			const maxFields30zgensym_d4b91a75c2094c05_31 = 3

			// -- templateUnmarshalMsg starts here--
			var totalEncodedFields30zgensym_d4b91a75c2094c05_31 uint32
			if !nbs.AlwaysNil {
				totalEncodedFields30zgensym_d4b91a75c2094c05_31, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
			}
			encodedFieldsLeft30zgensym_d4b91a75c2094c05_31 := totalEncodedFields30zgensym_d4b91a75c2094c05_31
			missingFieldsLeft30zgensym_d4b91a75c2094c05_31 := maxFields30zgensym_d4b91a75c2094c05_31 - totalEncodedFields30zgensym_d4b91a75c2094c05_31

			var nextMiss30zgensym_d4b91a75c2094c05_31 int32 = -1
			var found30zgensym_d4b91a75c2094c05_31 [maxFields30zgensym_d4b91a75c2094c05_31]bool
			var curField30zgensym_d4b91a75c2094c05_31 string

		doneWithStruct30zgensym_d4b91a75c2094c05_31:
			// First fill all the encoded fields, then
			// treat the remaining, missing fields, as Nil.
			for encodedFieldsLeft30zgensym_d4b91a75c2094c05_31 > 0 || missingFieldsLeft30zgensym_d4b91a75c2094c05_31 > 0 {
				//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft30zgensym_d4b91a75c2094c05_31, missingFieldsLeft30zgensym_d4b91a75c2094c05_31, msgp.ShowFound(found30zgensym_d4b91a75c2094c05_31[:]), unmarshalMsgFieldOrder30zgensym_d4b91a75c2094c05_31)
				if encodedFieldsLeft30zgensym_d4b91a75c2094c05_31 > 0 {
					encodedFieldsLeft30zgensym_d4b91a75c2094c05_31--
					field, bts, err = nbs.ReadMapKeyZC(bts)
					if err != nil {
						return
					}
					curField30zgensym_d4b91a75c2094c05_31 = msgp.UnsafeString(field)
				} else {
					//missing fields need handling
					if nextMiss30zgensym_d4b91a75c2094c05_31 < 0 {
						// set bts to contain just mnil (0xc0)
						bts = nbs.PushAlwaysNil(bts)
						nextMiss30zgensym_d4b91a75c2094c05_31 = 0
					}
					for nextMiss30zgensym_d4b91a75c2094c05_31 < maxFields30zgensym_d4b91a75c2094c05_31 && (found30zgensym_d4b91a75c2094c05_31[nextMiss30zgensym_d4b91a75c2094c05_31] || unmarshalMsgFieldSkip30zgensym_d4b91a75c2094c05_31[nextMiss30zgensym_d4b91a75c2094c05_31]) {
						nextMiss30zgensym_d4b91a75c2094c05_31++
					}
					if nextMiss30zgensym_d4b91a75c2094c05_31 == maxFields30zgensym_d4b91a75c2094c05_31 {
						// filled all the empty fields!
						break doneWithStruct30zgensym_d4b91a75c2094c05_31
					}
					missingFieldsLeft30zgensym_d4b91a75c2094c05_31--
					curField30zgensym_d4b91a75c2094c05_31 = unmarshalMsgFieldOrder30zgensym_d4b91a75c2094c05_31[nextMiss30zgensym_d4b91a75c2094c05_31]
				}
				//fmt.Printf("switching on curField: '%v'\n", curField30zgensym_d4b91a75c2094c05_31)
				switch curField30zgensym_d4b91a75c2094c05_31 {
				// -- templateUnmarshalMsg ends here --

				case "CzarLeaseEpoch_zid00_i64":
					found30zgensym_d4b91a75c2094c05_31[0] = true
					z.Vers.CzarLeaseEpoch, bts, err = nbs.ReadInt64Bytes(bts)

					if err != nil {
						return
					}
				case "Version_zid01_i64":
					found30zgensym_d4b91a75c2094c05_31[1] = true
					z.Vers.Version, bts, err = nbs.ReadInt64Bytes(bts)

					if err != nil {
						return
					}
				case "LeaseUpdateCounter_zid02_i64":
					found30zgensym_d4b91a75c2094c05_31[2] = true
					z.Vers.LeaseUpdateCounter, bts, err = nbs.ReadInt64Bytes(bts)

					if err != nil {
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						return
					}
				}
			}
			if nextMiss30zgensym_d4b91a75c2094c05_31 != -1 {
				bts = nbs.PopAlwaysNil()
			}

		case "SerzPeerDetails_zid02_slc":
			found28zgensym_d4b91a75c2094c05_29[2] = true
			if nbs.AlwaysNil {
				(z.SerzPeerDetails) = (z.SerzPeerDetails)[:0]
			} else {

				var zgensym_d4b91a75c2094c05_32 uint32
				zgensym_d4b91a75c2094c05_32, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.SerzPeerDetails) >= int(zgensym_d4b91a75c2094c05_32) {
					z.SerzPeerDetails = (z.SerzPeerDetails)[:zgensym_d4b91a75c2094c05_32]
				} else {
					z.SerzPeerDetails = make([]*PeerDetailPlus, zgensym_d4b91a75c2094c05_32)
				}
				for zgensym_d4b91a75c2094c05_18 := range z.SerzPeerDetails {
					// unmarshalGen.gPtr(): we have a BaseElem.

					// unmarshalGen.gPtr(): we have an IDENT:

					if nbs.AlwaysNil {
						if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] != nil {
							z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].UnmarshalMsg(msgp.OnlyNilSlice)
						}
					} else {
						// not nbs.AlwaysNil
						if msgp.IsNil(bts) {
							bts = bts[1:]
							if nil != z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] {
								z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].UnmarshalMsg(msgp.OnlyNilSlice)
							}
						} else {
							// not nbs.AlwaysNil and not IsNil(bts): have something to read

							if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] == nil {
								z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] = new(PeerDetailPlus)
							}

							bts, err = z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].UnmarshalMsg(bts)
							if err != nil {
								return
							}
						}
					}
				}
			}
		case "MemberLeaseDur_zid03_dur":
			found28zgensym_d4b91a75c2094c05_29[3] = true
			z.MemberLeaseDur, bts, err = nbs.ReadDurationBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss28zgensym_d4b91a75c2094c05_29 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of ReliableMembershipList
var unmarshalMsgFieldOrder28zgensym_d4b91a75c2094c05_29 = []string{"CzarName_zid00_str", "Vers_zid01_rct", "SerzPeerDetails_zid02_slc", "MemberLeaseDur_zid03_dur", ""}

var unmarshalMsgFieldSkip28zgensym_d4b91a75c2094c05_29 = []bool{false, false, false, false, true}

// fields of RMVersionTuple
var unmarshalMsgFieldOrder30zgensym_d4b91a75c2094c05_31 = []string{"CzarLeaseEpoch_zid00_i64", "Version_zid01_i64", "LeaseUpdateCounter_zid02_i64"}

var unmarshalMsgFieldSkip30zgensym_d4b91a75c2094c05_31 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ReliableMembershipList) Msgsize() (s int) {
	s = 1 + 19 + msgp.StringPrefixSize + len(z.CzarName) + 15 + 1 + 25 + msgp.Int64Size + 18 + msgp.Int64Size + 29 + msgp.Int64Size + 26 + msgp.ArrayHeaderSize
	for zgensym_d4b91a75c2094c05_18 := range z.SerzPeerDetails {
		if z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18] == nil {
			s += msgp.NilSize
		} else {
			s += z.SerzPeerDetails[zgensym_d4b91a75c2094c05_18].Msgsize()
		}
	}
	s += 25 + msgp.DurationSize
	return
}
func (z *ReliableMembershipList) Gstring() (r string) {
	r = "&ReliableMembershipList{\n"
	r += fmt.Sprintf("       CzarName: \"%v\",\n", z.CzarName)
	r += fmt.Sprintf("           Vers: %v,\n", z.Vers)
	r += fmt.Sprintf("SerzPeerDetails: %v,\n", z.SerzPeerDetails)
	r += fmt.Sprintf(" MemberLeaseDur: %v,\n", z.MemberLeaseDur)
	r += "}\n"
	return
}
