// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package tube

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
	"github.com/glycerine/rpc25519/tube/art"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *ArtTable) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields0zgensym_4984ea5d1b909aec_1 = 1

	// -- templateDecodeMsg starts here--
	var totalEncodedFields0zgensym_4984ea5d1b909aec_1 uint32
	totalEncodedFields0zgensym_4984ea5d1b909aec_1, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft0zgensym_4984ea5d1b909aec_1 := totalEncodedFields0zgensym_4984ea5d1b909aec_1
	missingFieldsLeft0zgensym_4984ea5d1b909aec_1 := maxFields0zgensym_4984ea5d1b909aec_1 - totalEncodedFields0zgensym_4984ea5d1b909aec_1

	var nextMiss0zgensym_4984ea5d1b909aec_1 int32 = -1
	var found0zgensym_4984ea5d1b909aec_1 [maxFields0zgensym_4984ea5d1b909aec_1]bool
	var curField0zgensym_4984ea5d1b909aec_1 string

doneWithStruct0zgensym_4984ea5d1b909aec_1:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft0zgensym_4984ea5d1b909aec_1 > 0 || missingFieldsLeft0zgensym_4984ea5d1b909aec_1 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft0zgensym_4984ea5d1b909aec_1, missingFieldsLeft0zgensym_4984ea5d1b909aec_1, msgp.ShowFound(found0zgensym_4984ea5d1b909aec_1[:]), decodeMsgFieldOrder0zgensym_4984ea5d1b909aec_1)
		if encodedFieldsLeft0zgensym_4984ea5d1b909aec_1 > 0 {
			encodedFieldsLeft0zgensym_4984ea5d1b909aec_1--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField0zgensym_4984ea5d1b909aec_1 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss0zgensym_4984ea5d1b909aec_1 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss0zgensym_4984ea5d1b909aec_1 = 0
			}
			for nextMiss0zgensym_4984ea5d1b909aec_1 < maxFields0zgensym_4984ea5d1b909aec_1 && (found0zgensym_4984ea5d1b909aec_1[nextMiss0zgensym_4984ea5d1b909aec_1] || decodeMsgFieldSkip0zgensym_4984ea5d1b909aec_1[nextMiss0zgensym_4984ea5d1b909aec_1]) {
				nextMiss0zgensym_4984ea5d1b909aec_1++
			}
			if nextMiss0zgensym_4984ea5d1b909aec_1 == maxFields0zgensym_4984ea5d1b909aec_1 {
				// filled all the empty fields!
				break doneWithStruct0zgensym_4984ea5d1b909aec_1
			}
			missingFieldsLeft0zgensym_4984ea5d1b909aec_1--
			curField0zgensym_4984ea5d1b909aec_1 = decodeMsgFieldOrder0zgensym_4984ea5d1b909aec_1[nextMiss0zgensym_4984ea5d1b909aec_1]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField0zgensym_4984ea5d1b909aec_1)
		switch curField0zgensym_4984ea5d1b909aec_1 {
		// -- templateDecodeMsg ends here --

		case "Tree_zid00_ptr":
			found0zgensym_4984ea5d1b909aec_1[0] = true
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}

				if z.Tree != nil {
					dc.PushAlwaysNil()
					err = z.Tree.DecodeMsg(dc)
					if err != nil {
						return
					}
					dc.PopAlwaysNil()
				}
			} else {
				// not Nil, we have something to read

				if z.Tree == nil {
					z.Tree = new(art.Tree)
				}
				dc.DedupIndexEachPtr(z.Tree)

				err = z.Tree.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss0zgensym_4984ea5d1b909aec_1 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of ArtTable
var decodeMsgFieldOrder0zgensym_4984ea5d1b909aec_1 = []string{"Tree_zid00_ptr"}

var decodeMsgFieldSkip0zgensym_4984ea5d1b909aec_1 = []bool{false}

// fieldsNotEmpty supports omitempty tags
func (z *ArtTable) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 1
	}
	var fieldsInUse uint32 = 1
	isempty[0] = (z.Tree == nil) // pointer, omitempty
	if isempty[0] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *ArtTable) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_4984ea5d1b909aec_2 [1]bool
	fieldsInUse_zgensym_4984ea5d1b909aec_3 := z.fieldsNotEmpty(empty_zgensym_4984ea5d1b909aec_2[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_4984ea5d1b909aec_3 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'ArtTable'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x41, 0x72, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_4984ea5d1b909aec_2[0] {
		// write "Tree_zid00_ptr"
		err = en.Append(0xae, 0x54, 0x72, 0x65, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x70, 0x74, 0x72)
		if err != nil {
			return err
		}
		// gPtr.encodeGen():

		if z.Tree == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Tree.EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ArtTable) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [1]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Tree_zid00_ptr"
		o = append(o, 0xae, 0x54, 0x72, 0x65, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x70, 0x74, 0x72)
		// marshalGen.gPtr()

		if z.Tree == nil {
			o = msgp.AppendNil(o)
		} else {
			// hmm.. no en, no place to check en.DedupWriteIsDup(z)

			o, err = z.Tree.MarshalMsg(o) // not is.iface
			if err != nil {
				return
			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ArtTable) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *ArtTable) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields4zgensym_4984ea5d1b909aec_5 = 1

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields4zgensym_4984ea5d1b909aec_5 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields4zgensym_4984ea5d1b909aec_5, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft4zgensym_4984ea5d1b909aec_5 := totalEncodedFields4zgensym_4984ea5d1b909aec_5
	missingFieldsLeft4zgensym_4984ea5d1b909aec_5 := maxFields4zgensym_4984ea5d1b909aec_5 - totalEncodedFields4zgensym_4984ea5d1b909aec_5

	var nextMiss4zgensym_4984ea5d1b909aec_5 int32 = -1
	var found4zgensym_4984ea5d1b909aec_5 [maxFields4zgensym_4984ea5d1b909aec_5]bool
	var curField4zgensym_4984ea5d1b909aec_5 string

doneWithStruct4zgensym_4984ea5d1b909aec_5:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft4zgensym_4984ea5d1b909aec_5 > 0 || missingFieldsLeft4zgensym_4984ea5d1b909aec_5 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft4zgensym_4984ea5d1b909aec_5, missingFieldsLeft4zgensym_4984ea5d1b909aec_5, msgp.ShowFound(found4zgensym_4984ea5d1b909aec_5[:]), unmarshalMsgFieldOrder4zgensym_4984ea5d1b909aec_5)
		if encodedFieldsLeft4zgensym_4984ea5d1b909aec_5 > 0 {
			encodedFieldsLeft4zgensym_4984ea5d1b909aec_5--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField4zgensym_4984ea5d1b909aec_5 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss4zgensym_4984ea5d1b909aec_5 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss4zgensym_4984ea5d1b909aec_5 = 0
			}
			for nextMiss4zgensym_4984ea5d1b909aec_5 < maxFields4zgensym_4984ea5d1b909aec_5 && (found4zgensym_4984ea5d1b909aec_5[nextMiss4zgensym_4984ea5d1b909aec_5] || unmarshalMsgFieldSkip4zgensym_4984ea5d1b909aec_5[nextMiss4zgensym_4984ea5d1b909aec_5]) {
				nextMiss4zgensym_4984ea5d1b909aec_5++
			}
			if nextMiss4zgensym_4984ea5d1b909aec_5 == maxFields4zgensym_4984ea5d1b909aec_5 {
				// filled all the empty fields!
				break doneWithStruct4zgensym_4984ea5d1b909aec_5
			}
			missingFieldsLeft4zgensym_4984ea5d1b909aec_5--
			curField4zgensym_4984ea5d1b909aec_5 = unmarshalMsgFieldOrder4zgensym_4984ea5d1b909aec_5[nextMiss4zgensym_4984ea5d1b909aec_5]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField4zgensym_4984ea5d1b909aec_5)
		switch curField4zgensym_4984ea5d1b909aec_5 {
		// -- templateUnmarshalMsg ends here --

		case "Tree_zid00_ptr":
			found4zgensym_4984ea5d1b909aec_5[0] = true
			// unmarshalGen.gPtr(): we have a BaseElem.

			// unmarshalGen.gPtr(): we have an IDENT:

			if nbs.AlwaysNil {
				if z.Tree != nil {
					z.Tree.UnmarshalMsg(msgp.OnlyNilSlice)
				}
			} else {
				// not nbs.AlwaysNil
				if msgp.IsNil(bts) {
					bts = bts[1:]
					if nil != z.Tree {
						z.Tree.UnmarshalMsg(msgp.OnlyNilSlice)
					}
				} else {
					// not nbs.AlwaysNil and not IsNil(bts): have something to read

					if z.Tree == nil {
						z.Tree = new(art.Tree)
					}

					bts, err = z.Tree.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss4zgensym_4984ea5d1b909aec_5 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of ArtTable
var unmarshalMsgFieldOrder4zgensym_4984ea5d1b909aec_5 = []string{"Tree_zid00_ptr"}

var unmarshalMsgFieldSkip4zgensym_4984ea5d1b909aec_5 = []bool{false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ArtTable) Msgsize() (s int) {
	s = 1 + 15
	if z.Tree == nil {
		s += msgp.NilSize
	} else {
		s += z.Tree.Msgsize()
	}
	return
}
func (z *ArtTable) Gstring() (r string) {
	r = "&ArtTable{\n"
	r += fmt.Sprintf("Tree: %v,\n", z.Tree)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *KVStore) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields8zgensym_4984ea5d1b909aec_9 = 2

	// -- templateDecodeMsg starts here--
	var totalEncodedFields8zgensym_4984ea5d1b909aec_9 uint32
	totalEncodedFields8zgensym_4984ea5d1b909aec_9, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft8zgensym_4984ea5d1b909aec_9 := totalEncodedFields8zgensym_4984ea5d1b909aec_9
	missingFieldsLeft8zgensym_4984ea5d1b909aec_9 := maxFields8zgensym_4984ea5d1b909aec_9 - totalEncodedFields8zgensym_4984ea5d1b909aec_9

	var nextMiss8zgensym_4984ea5d1b909aec_9 int32 = -1
	var found8zgensym_4984ea5d1b909aec_9 [maxFields8zgensym_4984ea5d1b909aec_9]bool
	var curField8zgensym_4984ea5d1b909aec_9 string

doneWithStruct8zgensym_4984ea5d1b909aec_9:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft8zgensym_4984ea5d1b909aec_9 > 0 || missingFieldsLeft8zgensym_4984ea5d1b909aec_9 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft8zgensym_4984ea5d1b909aec_9, missingFieldsLeft8zgensym_4984ea5d1b909aec_9, msgp.ShowFound(found8zgensym_4984ea5d1b909aec_9[:]), decodeMsgFieldOrder8zgensym_4984ea5d1b909aec_9)
		if encodedFieldsLeft8zgensym_4984ea5d1b909aec_9 > 0 {
			encodedFieldsLeft8zgensym_4984ea5d1b909aec_9--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField8zgensym_4984ea5d1b909aec_9 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss8zgensym_4984ea5d1b909aec_9 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss8zgensym_4984ea5d1b909aec_9 = 0
			}
			for nextMiss8zgensym_4984ea5d1b909aec_9 < maxFields8zgensym_4984ea5d1b909aec_9 && (found8zgensym_4984ea5d1b909aec_9[nextMiss8zgensym_4984ea5d1b909aec_9] || decodeMsgFieldSkip8zgensym_4984ea5d1b909aec_9[nextMiss8zgensym_4984ea5d1b909aec_9]) {
				nextMiss8zgensym_4984ea5d1b909aec_9++
			}
			if nextMiss8zgensym_4984ea5d1b909aec_9 == maxFields8zgensym_4984ea5d1b909aec_9 {
				// filled all the empty fields!
				break doneWithStruct8zgensym_4984ea5d1b909aec_9
			}
			missingFieldsLeft8zgensym_4984ea5d1b909aec_9--
			curField8zgensym_4984ea5d1b909aec_9 = decodeMsgFieldOrder8zgensym_4984ea5d1b909aec_9[nextMiss8zgensym_4984ea5d1b909aec_9]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField8zgensym_4984ea5d1b909aec_9)
		switch curField8zgensym_4984ea5d1b909aec_9 {
		// -- templateDecodeMsg ends here --

		case "Keys_zid00_slc":
			found8zgensym_4984ea5d1b909aec_9[0] = true
			var zgensym_4984ea5d1b909aec_10 uint32
			zgensym_4984ea5d1b909aec_10, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.Keys) >= int(zgensym_4984ea5d1b909aec_10) {
				z.Keys = (z.Keys)[:zgensym_4984ea5d1b909aec_10]
			} else {
				z.Keys = make([]Key, zgensym_4984ea5d1b909aec_10)
			}
			for zgensym_4984ea5d1b909aec_6 := range z.Keys {
				err = z.Keys[zgensym_4984ea5d1b909aec_6].DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		case "Vals_zid01_slc":
			found8zgensym_4984ea5d1b909aec_9[1] = true
			var zgensym_4984ea5d1b909aec_11 uint32
			zgensym_4984ea5d1b909aec_11, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.Vals) >= int(zgensym_4984ea5d1b909aec_11) {
				z.Vals = (z.Vals)[:zgensym_4984ea5d1b909aec_11]
			} else {
				z.Vals = make([]*ArtTable, zgensym_4984ea5d1b909aec_11)
			}
			for zgensym_4984ea5d1b909aec_7 := range z.Vals {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}

					z.Vals[zgensym_4984ea5d1b909aec_7] = nil
				} else {
					if z.Vals[zgensym_4984ea5d1b909aec_7] == nil {
						z.Vals[zgensym_4984ea5d1b909aec_7] = new(ArtTable)
					}
					dc.DedupIndexEachPtr(z.Vals[zgensym_4984ea5d1b909aec_7])

					const maxFields12zgensym_4984ea5d1b909aec_13 = 1

					// -- templateDecodeMsg starts here--
					var totalEncodedFields12zgensym_4984ea5d1b909aec_13 uint32
					totalEncodedFields12zgensym_4984ea5d1b909aec_13, err = dc.ReadMapHeader()
					if err != nil {
						return
					}
					encodedFieldsLeft12zgensym_4984ea5d1b909aec_13 := totalEncodedFields12zgensym_4984ea5d1b909aec_13
					missingFieldsLeft12zgensym_4984ea5d1b909aec_13 := maxFields12zgensym_4984ea5d1b909aec_13 - totalEncodedFields12zgensym_4984ea5d1b909aec_13

					var nextMiss12zgensym_4984ea5d1b909aec_13 int32 = -1
					var found12zgensym_4984ea5d1b909aec_13 [maxFields12zgensym_4984ea5d1b909aec_13]bool
					var curField12zgensym_4984ea5d1b909aec_13 string

				doneWithStruct12zgensym_4984ea5d1b909aec_13:
					// First fill all the encoded fields, then
					// treat the remaining, missing fields, as Nil.
					for encodedFieldsLeft12zgensym_4984ea5d1b909aec_13 > 0 || missingFieldsLeft12zgensym_4984ea5d1b909aec_13 > 0 {
						//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft12zgensym_4984ea5d1b909aec_13, missingFieldsLeft12zgensym_4984ea5d1b909aec_13, msgp.ShowFound(found12zgensym_4984ea5d1b909aec_13[:]), decodeMsgFieldOrder12zgensym_4984ea5d1b909aec_13)
						if encodedFieldsLeft12zgensym_4984ea5d1b909aec_13 > 0 {
							encodedFieldsLeft12zgensym_4984ea5d1b909aec_13--
							field, err = dc.ReadMapKeyPtr()
							if err != nil {
								return
							}
							curField12zgensym_4984ea5d1b909aec_13 = msgp.UnsafeString(field)
						} else {
							//missing fields need handling
							if nextMiss12zgensym_4984ea5d1b909aec_13 < 0 {
								// tell the reader to only give us Nils
								// until further notice.
								dc.PushAlwaysNil()
								nextMiss12zgensym_4984ea5d1b909aec_13 = 0
							}
							for nextMiss12zgensym_4984ea5d1b909aec_13 < maxFields12zgensym_4984ea5d1b909aec_13 && (found12zgensym_4984ea5d1b909aec_13[nextMiss12zgensym_4984ea5d1b909aec_13] || decodeMsgFieldSkip12zgensym_4984ea5d1b909aec_13[nextMiss12zgensym_4984ea5d1b909aec_13]) {
								nextMiss12zgensym_4984ea5d1b909aec_13++
							}
							if nextMiss12zgensym_4984ea5d1b909aec_13 == maxFields12zgensym_4984ea5d1b909aec_13 {
								// filled all the empty fields!
								break doneWithStruct12zgensym_4984ea5d1b909aec_13
							}
							missingFieldsLeft12zgensym_4984ea5d1b909aec_13--
							curField12zgensym_4984ea5d1b909aec_13 = decodeMsgFieldOrder12zgensym_4984ea5d1b909aec_13[nextMiss12zgensym_4984ea5d1b909aec_13]
						}
						//fmt.Printf("switching on curField: '%v'\n", curField12zgensym_4984ea5d1b909aec_13)
						switch curField12zgensym_4984ea5d1b909aec_13 {
						// -- templateDecodeMsg ends here --

						case "Tree_zid00_ptr":
							found12zgensym_4984ea5d1b909aec_13[0] = true
							if dc.IsNil() {
								err = dc.ReadNil()
								if err != nil {
									return
								}

								if z.Vals[zgensym_4984ea5d1b909aec_7].Tree != nil {
									dc.PushAlwaysNil()
									err = z.Vals[zgensym_4984ea5d1b909aec_7].Tree.DecodeMsg(dc)
									if err != nil {
										return
									}
									dc.PopAlwaysNil()
								}
							} else {
								// not Nil, we have something to read

								if z.Vals[zgensym_4984ea5d1b909aec_7].Tree == nil {
									z.Vals[zgensym_4984ea5d1b909aec_7].Tree = new(art.Tree)
								}
								dc.DedupIndexEachPtr(z.Vals[zgensym_4984ea5d1b909aec_7].Tree)

								err = z.Vals[zgensym_4984ea5d1b909aec_7].Tree.DecodeMsg(dc)
								if err != nil {
									return
								}
							}
						default:
							err = dc.Skip()
							if err != nil {
								return
							}
						}
					}
					if nextMiss12zgensym_4984ea5d1b909aec_13 != -1 {
						dc.PopAlwaysNil()
					}

				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss8zgensym_4984ea5d1b909aec_9 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of KVStore
var decodeMsgFieldOrder8zgensym_4984ea5d1b909aec_9 = []string{"Keys_zid00_slc", "Vals_zid01_slc"}

var decodeMsgFieldSkip8zgensym_4984ea5d1b909aec_9 = []bool{false, false}

// fields of ArtTable
var decodeMsgFieldOrder12zgensym_4984ea5d1b909aec_13 = []string{"Tree_zid00_ptr"}

var decodeMsgFieldSkip12zgensym_4984ea5d1b909aec_13 = []bool{false}

// fieldsNotEmpty supports omitempty tags
func (z *KVStore) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 2
	}
	var fieldsInUse uint32 = 2
	isempty[0] = (len(z.Keys) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Vals) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *KVStore) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_4984ea5d1b909aec_14 [2]bool
	fieldsInUse_zgensym_4984ea5d1b909aec_15 := z.fieldsNotEmpty(empty_zgensym_4984ea5d1b909aec_14[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_4984ea5d1b909aec_15 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'KVStore'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_4984ea5d1b909aec_14[0] {
		// write "Keys_zid00_slc"
		err = en.Append(0xae, 0x4b, 0x65, 0x79, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x6c, 0x63)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.Keys)))
		if err != nil {
			return
		}
		for zgensym_4984ea5d1b909aec_6 := range z.Keys {
			err = z.Keys[zgensym_4984ea5d1b909aec_6].EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}

	if !empty_zgensym_4984ea5d1b909aec_14[1] {
		// write "Vals_zid01_slc"
		err = en.Append(0xae, 0x56, 0x61, 0x6c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x6c, 0x63)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.Vals)))
		if err != nil {
			return
		}
		for zgensym_4984ea5d1b909aec_7 := range z.Vals {
			// gPtr.encodeGen():

			if z.Vals[zgensym_4984ea5d1b909aec_7] == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {

				// honor the omitempty tags
				var empty_zgensym_4984ea5d1b909aec_16 [1]bool
				fieldsInUse_zgensym_4984ea5d1b909aec_17 := z.Vals[zgensym_4984ea5d1b909aec_7].fieldsNotEmpty(empty_zgensym_4984ea5d1b909aec_16[:])

				// map header
				err = en.WriteMapHeader(fieldsInUse_zgensym_4984ea5d1b909aec_17 + 1)
				if err != nil {
					return err
				}

				// runtime struct type identification for 'ArtTable'
				err = en.Append(0xa1, 0x40)
				if err != nil {
					return err
				}
				err = en.WriteStringFromBytes([]byte{0x41, 0x72, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65})
				if err != nil {
					return err
				}

				if !empty_zgensym_4984ea5d1b909aec_16[0] {
					// write "Tree_zid00_ptr"
					err = en.Append(0xae, 0x54, 0x72, 0x65, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x70, 0x74, 0x72)
					if err != nil {
						return err
					}
					// gPtr.encodeGen():

					if z.Vals[zgensym_4984ea5d1b909aec_7].Tree == nil {
						err = en.WriteNil()
						if err != nil {
							return
						}
					} else {
						err = z.Vals[zgensym_4984ea5d1b909aec_7].Tree.EncodeMsg(en)
						if err != nil {
							return
						}
					}
				}

			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *KVStore) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [2]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Keys_zid00_slc"
		o = append(o, 0xae, 0x4b, 0x65, 0x79, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x6c, 0x63)
		o = msgp.AppendArrayHeader(o, uint32(len(z.Keys)))
		for zgensym_4984ea5d1b909aec_6 := range z.Keys {
			o, err = z.Keys[zgensym_4984ea5d1b909aec_6].MarshalMsg(o) // not is.iface
			if err != nil {
				return
			}
		}
	}

	if !empty[1] {
		// string "Vals_zid01_slc"
		o = append(o, 0xae, 0x56, 0x61, 0x6c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x6c, 0x63)
		o = msgp.AppendArrayHeader(o, uint32(len(z.Vals)))
		for zgensym_4984ea5d1b909aec_7 := range z.Vals {
			// marshalGen.gPtr()

			if z.Vals[zgensym_4984ea5d1b909aec_7] == nil {
				o = msgp.AppendNil(o)
			} else {
				// hmm.. no en, no place to check en.DedupWriteIsDup(z)

				// honor the omitempty tags
				var empty [1]bool
				fieldsInUse := z.Vals[zgensym_4984ea5d1b909aec_7].fieldsNotEmpty(empty[:])
				o = msgp.AppendMapHeader(o, fieldsInUse)

				if !empty[0] {
					// string "Tree_zid00_ptr"
					o = append(o, 0xae, 0x54, 0x72, 0x65, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x70, 0x74, 0x72)
					// marshalGen.gPtr()

					if z.Vals[zgensym_4984ea5d1b909aec_7].Tree == nil {
						o = msgp.AppendNil(o)
					} else {
						// hmm.. no en, no place to check en.DedupWriteIsDup(z)

						o, err = z.Vals[zgensym_4984ea5d1b909aec_7].Tree.MarshalMsg(o) // not is.iface
						if err != nil {
							return
						}
					}
				}

			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KVStore) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *KVStore) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields18zgensym_4984ea5d1b909aec_19 = 2

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields18zgensym_4984ea5d1b909aec_19 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields18zgensym_4984ea5d1b909aec_19, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft18zgensym_4984ea5d1b909aec_19 := totalEncodedFields18zgensym_4984ea5d1b909aec_19
	missingFieldsLeft18zgensym_4984ea5d1b909aec_19 := maxFields18zgensym_4984ea5d1b909aec_19 - totalEncodedFields18zgensym_4984ea5d1b909aec_19

	var nextMiss18zgensym_4984ea5d1b909aec_19 int32 = -1
	var found18zgensym_4984ea5d1b909aec_19 [maxFields18zgensym_4984ea5d1b909aec_19]bool
	var curField18zgensym_4984ea5d1b909aec_19 string

doneWithStruct18zgensym_4984ea5d1b909aec_19:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft18zgensym_4984ea5d1b909aec_19 > 0 || missingFieldsLeft18zgensym_4984ea5d1b909aec_19 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft18zgensym_4984ea5d1b909aec_19, missingFieldsLeft18zgensym_4984ea5d1b909aec_19, msgp.ShowFound(found18zgensym_4984ea5d1b909aec_19[:]), unmarshalMsgFieldOrder18zgensym_4984ea5d1b909aec_19)
		if encodedFieldsLeft18zgensym_4984ea5d1b909aec_19 > 0 {
			encodedFieldsLeft18zgensym_4984ea5d1b909aec_19--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField18zgensym_4984ea5d1b909aec_19 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss18zgensym_4984ea5d1b909aec_19 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss18zgensym_4984ea5d1b909aec_19 = 0
			}
			for nextMiss18zgensym_4984ea5d1b909aec_19 < maxFields18zgensym_4984ea5d1b909aec_19 && (found18zgensym_4984ea5d1b909aec_19[nextMiss18zgensym_4984ea5d1b909aec_19] || unmarshalMsgFieldSkip18zgensym_4984ea5d1b909aec_19[nextMiss18zgensym_4984ea5d1b909aec_19]) {
				nextMiss18zgensym_4984ea5d1b909aec_19++
			}
			if nextMiss18zgensym_4984ea5d1b909aec_19 == maxFields18zgensym_4984ea5d1b909aec_19 {
				// filled all the empty fields!
				break doneWithStruct18zgensym_4984ea5d1b909aec_19
			}
			missingFieldsLeft18zgensym_4984ea5d1b909aec_19--
			curField18zgensym_4984ea5d1b909aec_19 = unmarshalMsgFieldOrder18zgensym_4984ea5d1b909aec_19[nextMiss18zgensym_4984ea5d1b909aec_19]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField18zgensym_4984ea5d1b909aec_19)
		switch curField18zgensym_4984ea5d1b909aec_19 {
		// -- templateUnmarshalMsg ends here --

		case "Keys_zid00_slc":
			found18zgensym_4984ea5d1b909aec_19[0] = true
			if nbs.AlwaysNil {
				(z.Keys) = (z.Keys)[:0]
			} else {

				var zgensym_4984ea5d1b909aec_20 uint32
				zgensym_4984ea5d1b909aec_20, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.Keys) >= int(zgensym_4984ea5d1b909aec_20) {
					z.Keys = (z.Keys)[:zgensym_4984ea5d1b909aec_20]
				} else {
					z.Keys = make([]Key, zgensym_4984ea5d1b909aec_20)
				}
				for zgensym_4984ea5d1b909aec_6 := range z.Keys {
					bts, err = z.Keys[zgensym_4984ea5d1b909aec_6].UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		case "Vals_zid01_slc":
			found18zgensym_4984ea5d1b909aec_19[1] = true
			if nbs.AlwaysNil {
				(z.Vals) = (z.Vals)[:0]
			} else {

				var zgensym_4984ea5d1b909aec_21 uint32
				zgensym_4984ea5d1b909aec_21, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.Vals) >= int(zgensym_4984ea5d1b909aec_21) {
					z.Vals = (z.Vals)[:zgensym_4984ea5d1b909aec_21]
				} else {
					z.Vals = make([]*ArtTable, zgensym_4984ea5d1b909aec_21)
				}
				for zgensym_4984ea5d1b909aec_7 := range z.Vals {
					// default gPtr logic.
					if nbs.PeekNil(bts) && z.Vals[zgensym_4984ea5d1b909aec_7] == nil {
						// consume the nil
						bts, err = nbs.ReadNilBytes(bts)
						if err != nil {
							return
						}
					} else {
						// read as-if the wire has bytes, letting nbs take care of nils.

						if z.Vals[zgensym_4984ea5d1b909aec_7] == nil {
							z.Vals[zgensym_4984ea5d1b909aec_7] = new(ArtTable)
						}

						const maxFields22zgensym_4984ea5d1b909aec_23 = 1

						// -- templateUnmarshalMsg starts here--
						var totalEncodedFields22zgensym_4984ea5d1b909aec_23 uint32
						if !nbs.AlwaysNil {
							totalEncodedFields22zgensym_4984ea5d1b909aec_23, bts, err = nbs.ReadMapHeaderBytes(bts)
							if err != nil {
								return
							}
						}
						encodedFieldsLeft22zgensym_4984ea5d1b909aec_23 := totalEncodedFields22zgensym_4984ea5d1b909aec_23
						missingFieldsLeft22zgensym_4984ea5d1b909aec_23 := maxFields22zgensym_4984ea5d1b909aec_23 - totalEncodedFields22zgensym_4984ea5d1b909aec_23

						var nextMiss22zgensym_4984ea5d1b909aec_23 int32 = -1
						var found22zgensym_4984ea5d1b909aec_23 [maxFields22zgensym_4984ea5d1b909aec_23]bool
						var curField22zgensym_4984ea5d1b909aec_23 string

					doneWithStruct22zgensym_4984ea5d1b909aec_23:
						// First fill all the encoded fields, then
						// treat the remaining, missing fields, as Nil.
						for encodedFieldsLeft22zgensym_4984ea5d1b909aec_23 > 0 || missingFieldsLeft22zgensym_4984ea5d1b909aec_23 > 0 {
							//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft22zgensym_4984ea5d1b909aec_23, missingFieldsLeft22zgensym_4984ea5d1b909aec_23, msgp.ShowFound(found22zgensym_4984ea5d1b909aec_23[:]), unmarshalMsgFieldOrder22zgensym_4984ea5d1b909aec_23)
							if encodedFieldsLeft22zgensym_4984ea5d1b909aec_23 > 0 {
								encodedFieldsLeft22zgensym_4984ea5d1b909aec_23--
								field, bts, err = nbs.ReadMapKeyZC(bts)
								if err != nil {
									return
								}
								curField22zgensym_4984ea5d1b909aec_23 = msgp.UnsafeString(field)
							} else {
								//missing fields need handling
								if nextMiss22zgensym_4984ea5d1b909aec_23 < 0 {
									// set bts to contain just mnil (0xc0)
									bts = nbs.PushAlwaysNil(bts)
									nextMiss22zgensym_4984ea5d1b909aec_23 = 0
								}
								for nextMiss22zgensym_4984ea5d1b909aec_23 < maxFields22zgensym_4984ea5d1b909aec_23 && (found22zgensym_4984ea5d1b909aec_23[nextMiss22zgensym_4984ea5d1b909aec_23] || unmarshalMsgFieldSkip22zgensym_4984ea5d1b909aec_23[nextMiss22zgensym_4984ea5d1b909aec_23]) {
									nextMiss22zgensym_4984ea5d1b909aec_23++
								}
								if nextMiss22zgensym_4984ea5d1b909aec_23 == maxFields22zgensym_4984ea5d1b909aec_23 {
									// filled all the empty fields!
									break doneWithStruct22zgensym_4984ea5d1b909aec_23
								}
								missingFieldsLeft22zgensym_4984ea5d1b909aec_23--
								curField22zgensym_4984ea5d1b909aec_23 = unmarshalMsgFieldOrder22zgensym_4984ea5d1b909aec_23[nextMiss22zgensym_4984ea5d1b909aec_23]
							}
							//fmt.Printf("switching on curField: '%v'\n", curField22zgensym_4984ea5d1b909aec_23)
							switch curField22zgensym_4984ea5d1b909aec_23 {
							// -- templateUnmarshalMsg ends here --

							case "Tree_zid00_ptr":
								found22zgensym_4984ea5d1b909aec_23[0] = true
								// unmarshalGen.gPtr(): we have a BaseElem.

								// unmarshalGen.gPtr(): we have an IDENT:

								if nbs.AlwaysNil {
									if z.Vals[zgensym_4984ea5d1b909aec_7].Tree != nil {
										z.Vals[zgensym_4984ea5d1b909aec_7].Tree.UnmarshalMsg(msgp.OnlyNilSlice)
									}
								} else {
									// not nbs.AlwaysNil
									if msgp.IsNil(bts) {
										bts = bts[1:]
										if nil != z.Vals[zgensym_4984ea5d1b909aec_7].Tree {
											z.Vals[zgensym_4984ea5d1b909aec_7].Tree.UnmarshalMsg(msgp.OnlyNilSlice)
										}
									} else {
										// not nbs.AlwaysNil and not IsNil(bts): have something to read

										if z.Vals[zgensym_4984ea5d1b909aec_7].Tree == nil {
											z.Vals[zgensym_4984ea5d1b909aec_7].Tree = new(art.Tree)
										}

										bts, err = z.Vals[zgensym_4984ea5d1b909aec_7].Tree.UnmarshalMsg(bts)
										if err != nil {
											return
										}
									}
								}
							default:
								bts, err = msgp.Skip(bts)
								if err != nil {
									return
								}
							}
						}
						if nextMiss22zgensym_4984ea5d1b909aec_23 != -1 {
							bts = nbs.PopAlwaysNil()
						}

					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss18zgensym_4984ea5d1b909aec_19 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of KVStore
var unmarshalMsgFieldOrder18zgensym_4984ea5d1b909aec_19 = []string{"Keys_zid00_slc", "Vals_zid01_slc"}

var unmarshalMsgFieldSkip18zgensym_4984ea5d1b909aec_19 = []bool{false, false}

// fields of ArtTable
var unmarshalMsgFieldOrder22zgensym_4984ea5d1b909aec_23 = []string{"Tree_zid00_ptr"}

var unmarshalMsgFieldSkip22zgensym_4984ea5d1b909aec_23 = []bool{false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *KVStore) Msgsize() (s int) {
	s = 1 + 15 + msgp.ArrayHeaderSize
	for zgensym_4984ea5d1b909aec_6 := range z.Keys {
		s += z.Keys[zgensym_4984ea5d1b909aec_6].Msgsize()
	}
	s += 15 + msgp.ArrayHeaderSize
	for zgensym_4984ea5d1b909aec_7 := range z.Vals {
		if z.Vals[zgensym_4984ea5d1b909aec_7] == nil {
			s += msgp.NilSize
		} else {
			s += 1 + 15
			if z.Vals[zgensym_4984ea5d1b909aec_7].Tree == nil {
				s += msgp.NilSize
			} else {
				s += z.Vals[zgensym_4984ea5d1b909aec_7].Tree.Msgsize()
			}
		}
	}
	return
}
func (z *KVStore) Gstring() (r string) {
	r = "&KVStore{\n"
	r += fmt.Sprintf("Keys: %v,\n", z.Keys)
	r += fmt.Sprintf("Vals: %v,\n", z.Vals)
	r += "}\n"
	return
}
