        before complete_ready {
            require live(n);

            complete_try(n) := true;
            complete_try(N) := false;

            if live(n) & ready(n) & pending(n) & pending_rmw(n) & rmw_conflict(pending_ts(n)) {
                epoch_done(E) := epoch_done(E) | E = ready_epoch(n);
                pending(n) := false;
                pending_rmw(n) := false;
                acked(n,A) := false;
                ready(n) := false;
                state(n) := hs_invalid;
            } else {
            if live(n) & ready(n) & pending(n) & ~pending_rmw(n) & write_conflict(pending_ts(n)) {
                epoch_done(E) := epoch_done(E) | E = ready_epoch(n);
                pending(n) := false;
                pending_rmw(n) := false;
                acked(n,A) := false;
                ready(n) := false;

                if state(n) = hs_invalid_write {
                    state(n) := hs_invalid;
                };
            } else {
            if live(n) & ready(n) & pending(n) & pending_ts(n) = cur_ts(n) & (state(n) = hs_write | state(n) = hs_replay) &
               (cur_rmw(n) -> ~rmw_conflict(cur_ts(n))) & (~cur_rmw(n) -> ~write_conflict(cur_ts(n))) {
                completed(cur_ts(n)) := true;
                rmw_conflict(T) := rmw_conflict(T) |
                    (ts_rmw(T) & T ~= cur_ts(n) & same_version(cur_ts(n),T)) |
                    (~ts_rmw(cur_ts(n)) & ts_rmw(T) & (same_version(T,cur_ts(n)) | next_version(cur_ts(n),T)));
                write_conflict(T) := write_conflict(T) |
                    (ts_rmw(cur_ts(n)) & ~ts_rmw(T) & (same_version(cur_ts(n),T) | next_version(T,cur_ts(n))));
                val_msg(cur_ts(n)) := true;
                state(n) := hs_valid;
                epoch_done(E) := epoch_done(E) | E = ready_epoch(n);
                pending(n) := false;
                pending_rmw(n) := false;
                acked(n,A) := false;
                ready(n) := false;
            } else {
                if live(n) & ready(n) & pending(n) & lt(pending_ts(n),cur_ts(n)) & ~write_conflict(pending_ts(n)) {
                    completed(pending_ts(n)) := true;
                    rmw_conflict(T) := rmw_conflict(T) |
                        (ts_rmw(T) & T ~= pending_ts(n) & same_version(pending_ts(n),T)) |
                        (~ts_rmw(pending_ts(n)) & ts_rmw(T) & (same_version(T,pending_ts(n)) | next_version(pending_ts(n),T)));
                    write_conflict(T) := write_conflict(T) |
                        (ts_rmw(pending_ts(n)) & ~ts_rmw(T) & (same_version(pending_ts(n),T) | next_version(T,pending_ts(n))));
                    epoch_done(E) := epoch_done(E) | E = ready_epoch(n);
                    pending(n) := false;
                    pending_rmw(n) := false;
                    acked(n,A) := false;
                    ready(n) := false;

                    if state(n) = hs_invalid_write {
                        state(n) := hs_invalid;
                    }
                }
            }
            }
            }
        }

