
        before local_write {
            require false;
        }

        before receive_write_inv {
            require false;
        }

        before complete_overwritten {
            require false;
        }

        before complete_ready {
            require false;
        }

        before o3_observe_quorum {
            require false;
        }

        before o3_complete {
            require false;
        }

        before replay_after_failure {
            require false;
        }

        before fail {
            require false;
        }
