        invariant ready(N) -> live(N)
        invariant ready(N) -> seen_epoch(ready_epoch(N))
        invariant ready(N) -> ready_epoch(N) ~= init_epoch
        invariant ready(N) -> ready_epoch_active(ready_epoch(N))
        invariant epoch_done(E) -> seen_epoch(E)
        invariant ready_epoch_active(E) -> seen_epoch(E)
        invariant ~complete_try(N)
        invariant ~o3_try(N,C,T)
        invariant ready_task = ready_finish
        invariant o3_task = o3_finish
