#lang ivy1.7

export hermes_protocol.ambient.idle
export hermes_protocol.ambient.collect_ack
export hermes_protocol.ambient.make_ready
export hermes_protocol.ambient.finish_current
export hermes_protocol.ambient.finish_overwritten
export hermes_protocol.ambient.complete_ready_driver
export hermes_protocol.ambient.finish_conflicted_ready
export hermes_protocol.ambient.scenario_write_quorum
export hermes_protocol.ambient.scenario_rmw_quorum
export hermes_protocol.ambient.scenario_overwritten_write
export hermes_protocol.ambient.scenario_rmw_aborted_by_write
export hermes_protocol.ambient.scenario_rmw_race_pushback
export hermes_protocol.ambient.scenario_writer_fail_replay

attribute hermes_protocol.ambient.idle.weight = "0.02"
attribute hermes_protocol.ambient.collect_ack.weight = "2.0"
attribute hermes_protocol.ambient.make_ready.weight = "1.5"
attribute hermes_protocol.ambient.finish_current.weight = "1.5"
attribute hermes_protocol.ambient.finish_overwritten.weight = "1.5"
attribute hermes_protocol.ambient.complete_ready_driver.weight = "1.0"
attribute hermes_protocol.ambient.finish_conflicted_ready.weight = "1.0"
attribute hermes_protocol.ambient.scenario_write_quorum.weight = "0.75"
attribute hermes_protocol.ambient.scenario_rmw_quorum.weight = "0.75"
attribute hermes_protocol.ambient.scenario_overwritten_write.weight = "0.75"
attribute hermes_protocol.ambient.scenario_rmw_aborted_by_write.weight = "0.75"
attribute hermes_protocol.ambient.scenario_rmw_race_pushback.weight = "0.75"
attribute hermes_protocol.ambient.scenario_writer_fail_replay.weight = "0.75"
